[graph]
all-features = true

[advisories]
version = 2
yanked = "deny"
unmaintained = "workspace"

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
  "https://github.com/facebook/pyrefly",
  "https://github.com/yangdanny97/lsp-types",
]
