"""Machine-contract encoding helpers shared with the Rust daemon."""

from . import model_registries as registries

from .identity import (
    SOURCE_CONTEXT_ID,
    CbefField,
    CbefRecord,
    CbefValue,
    DerivedIdentity,
    IdentityDomain,
    IdentityError,
    TypeCode,
    WorkspacePath,
    canonical_type_term,
    decode_public_id,
    decode_record,
    derive_identity,
    encode_public_id,
    encode_record,
    validate_workspace_paths,
)
from .index import (
    ExternalDriverBudget,
    ModelArtifactIndex,
    ModelArtifactRecord,
    NamedResourceProfile,
    model_artifact_index,
    model_artifact_index_bytes,
    model_artifact_index_digest,
)
from .json import (
    PROFILE,
    CanonicalJsonError,
    canonicalize_json,
    canonicalize_value,
    checksum,
    non_string_map_records,
    validate_bytes,
    validate_checksum,
    validate_int64,
    validate_lowercase_public,
    validate_uint64,
)

__all__ = [
    "PROFILE",
    "ExternalDriverBudget",
    "ModelArtifactIndex",
    "ModelArtifactRecord",
    "NamedResourceProfile",
    "CbefField",
    "CbefRecord",
    "CbefValue",
    "CanonicalJsonError",
    "DerivedIdentity",
    "IdentityDomain",
    "IdentityError",
    "SOURCE_CONTEXT_ID",
    "TypeCode",
    "WorkspacePath",
    "model_artifact_index",
    "model_artifact_index_bytes",
    "model_artifact_index_digest",
    "canonicalize_json",
    "canonicalize_value",
    "canonical_type_term",
    "checksum",
    "decode_public_id",
    "decode_record",
    "derive_identity",
    "encode_public_id",
    "encode_record",
    "non_string_map_records",
    "validate_bytes",
    "validate_checksum",
    "validate_int64",
    "validate_lowercase_public",
    "validate_uint64",
    "validate_workspace_paths",
    "registries",
]
