# @generated by codefabric-model; edit registry authorities instead.
from enum import IntEnum, IntFlag
from types import MappingProxyType


class IdentityDomain(IntEnum):
    WORKSPACE = 1
    REPOSITORY = 2
    WORKTREE = 3
    ANALYSIS_CONTEXT = 4
    CONTEXT_SET = 5
    SOURCE_FILE = 6
    OWNER = 7
    ENTITY = 8
    RELATION_FACT = 9
    PROPERTY_FACT = 10
    TYPE = 11
    PUBLICATION = 12
    SERVING_SNAPSHOT = 13
    RESULT_ARTIFACT = 14
    SOURCE_CONTEXT = 15
    UNKNOWN_REMAINDER = 16
    ROOT_AUTHORIZATION = 17


class TypeCode(IntEnum):
    ABSENT = 0
    BYTES = 1
    UTF8 = 2
    RAW_PATH = 3
    UNSIGNED = 4
    SIGNED = 5
    BOOLEAN = 6
    ID = 7
    DIGEST = 8
    ORDERED_LIST = 9
    SET = 10
    MAP = 11
    TAGGED_UNION = 12


class EvidenceCertainty(IntEnum):
    SOURCE_EXACT = 10
    COMPILER_EXACT = 20
    STATIC_SEMANTIC = 30
    SOUND_MAY = 40
    MODELLED = 50
    HEURISTIC = 60
    UNRESOLVED = 70


class ResolutionClass(IntEnum):
    EXACT = 10
    STATICALLY_RESOLVED = 20
    SOUND_POSSIBLE = 30
    POSSIBLE = 40
    MODELLED = 50
    HEURISTIC = 60
    UNRESOLVED = 70
    UNAVAILABLE = 80
    NOT_APPLICABLE = 90


class Directness(IntEnum):
    DIRECT = 10
    TRANSITIVE = 20
    SUMMARY = 30
    NOT_APPLICABLE = 40


class Completeness(IntEnum):
    COMPLETE = 10
    PARTIAL = 20
    INDETERMINATE = 30
    UNAVAILABLE = 40
    NOT_APPLICABLE = 50


class OwnerCapabilityState(IntEnum):
    CURRENT = 10
    PENDING = 20
    INVALIDATED = 30
    PARTIAL = 40
    UNAVAILABLE_PARSE = 50
    UNAVAILABLE_COMPILE = 60
    UNAVAILABLE_PROVIDER = 70
    UNAVAILABLE_DERIVATION = 80
    EXCLUDED = 90
    UNSUPPORTED = 100
    REMOVED = 110
    NOT_APPLICABLE = 120


class ProviderRunState(IntEnum):
    QUEUED = 10
    RUNNING = 20
    SUCCEEDED = 30
    PARTIAL = 40
    FAILED = 50
    TIMED_OUT = 60
    CANCELLED = 70
    SUPERSEDED = 80
    CRASHED = 90
    PROTOCOL_ERROR = 100
    STALE_RESULT = 110
    STALE_GIT_BASELINE = 120


class QueryExecutionState(IntEnum):
    ACCEPTED = 10
    RUNNING = 20
    COMPLETE = 30
    FAILED = 40
    CANCELLED = 50
    DEADLINE_EXCEEDED = 60
    NOT_EXECUTED_DEPENDENCY = 70


class QueryForm(IntEnum):
    FIND_ENTITIES = 10
    RETRIEVE_FACTS = 20
    FOLLOW_RELATIONSHIPS = 30
    FIND_PATHS = 40
    MATCH_PATTERN = 50
    COMBINE_RESULTS = 60
    SUMMARIZE_FACTS = 70
    RETRIEVE_SOURCE_CONTEXT = 80


class QueryAvailabilityState(IntEnum):
    AVAILABLE = 10
    PARTIAL = 20
    UNAVAILABLE = 30
    NOT_APPLICABLE = 40


class CompletenessState(IntEnum):
    COMPLETE = 10
    PARTIAL = 20
    INDETERMINATE = 30
    UNAVAILABLE = 40
    NOT_APPLICABLE = 50


class FreshnessState(IntEnum):
    CURRENT = 10
    POTENTIALLY_STALE = 20
    UNAVAILABLE = 30


class LimitState(IntEnum):
    NOT_APPLIED = 10
    EXPLICIT_LIMIT_REACHED = 20
    HARD_LIMIT_REJECTED = 30


class DependencyState(IntEnum):
    READY = 10
    FAILED_DEPENDENCY = 20
    NOT_APPLICABLE = 30


class DurablePublicationState(IntEnum):
    STAGING = 10
    VALIDATING = 20
    VALIDATED = 30
    COMMITTING = 40
    COMPLETE = 50
    FAILED = 60
    ABANDONED = 70


class ServingActivationState(IntEnum):
    BUILDING = 10
    VALIDATING = 20
    READY = 30
    ACTIVE = 40
    RETIRED = 50
    FAILED = 60


class SnapshotLeaseKind(IntEnum):
    QUERY = 10
    RESULT_ARTIFACT = 20
    RESOURCE_READ = 30
    MAINTENANCE = 40


class SnapshotLeaseState(IntEnum):
    ACTIVE = 10
    RELEASING = 20
    RELEASED = 30
    EXPIRED = 40
    ORPHANED = 50


class SourceTrustState(IntEnum):
    UNVERIFIED = 10
    VERIFYING = 20
    CURRENT = 30
    POTENTIALLY_STALE = 40
    UNAVAILABLE = 50


class EventStreamHealth(IntEnum):
    HEALTHY = 10
    RESCAN_REQUIRED = 20
    DEGRADED = 30
    UNAVAILABLE = 40


class GitAccelerationStatus(IntEnum):
    NOT_A_GIT_WORKTREE = 10
    GIT_UNAVAILABLE = 20
    GIT_READY = 30
    GIT_METADATA_DIRTY = 40
    GIT_SCANNING = 50
    GIT_OPERATION_IN_PROGRESS = 60
    GIT_BULK_RECONCILING = 70
    GIT_DEGRADED = 80


class EffectKind(IntEnum):
    READ_MEMORY = 10
    WRITE_MEMORY = 20
    ALLOCATE_MEMORY = 30
    DEALLOCATE_MEMORY = 40
    READ_FILE = 50
    WRITE_FILE = 60
    READ_NETWORK = 70
    WRITE_NETWORK = 80
    READ_DATABASE = 90
    WRITE_DATABASE = 100
    BEGIN_TRANSACTION = 110
    COMMIT_TRANSACTION = 120
    ROLLBACK_TRANSACTION = 130
    READ_STANDARD_INPUT = 140
    WRITE_STANDARD_OUTPUT = 150
    LOG_OR_TELEMETRY = 160
    READ_ENVIRONMENT = 170
    WRITE_ENVIRONMENT = 180
    SPAWN_PROCESS = 190
    SPAWN_THREAD_OR_TASK = 200
    BLOCK_THREAD = 210
    SLEEP_OR_WAIT = 220
    LOAD_DYNAMIC_LIBRARY = 230
    ACQUIRE_LOCK = 240
    RELEASE_LOCK = 250
    SEND_CHANNEL = 260
    RECEIVE_CHANNEL = 270
    READ_TIME = 280
    READ_RANDOMNESS = 290
    READ_GLOBAL_STATE = 300
    WRITE_GLOBAL_STATE = 310
    RAISE_EXCEPTION = 320
    PANIC_OR_ABORT = 330
    UNSAFE_OPERATION = 340
    FFI_CALL = 350
    DYNAMIC_CODE_EXECUTION = 360
    UNKNOWN_EXTERNAL_EFFECT = 370


class ResourceKind(IntEnum):
    FILE_HANDLE = 10
    SOCKET_OR_CONNECTION = 20
    DATABASE_CONNECTION_OR_TRANSACTION = 30
    LOCK_GUARD = 40
    CHANNEL_ENDPOINT = 50
    PROCESS_HANDLE = 60
    THREAD_OR_TASK_HANDLE = 70
    MEMORY_ALLOCATION = 80
    USER_DEFINED_MODELLED_RESOURCE = 90
    UNKNOWN_RESOURCE = 100


class ProviderCode(IntEnum):
    TREE_SITTER = 10
    RUFF_PYTHON = 20
    PYREFLY_PYTHON = 30
    RUSTC_MIR = 40
    CODEFABRIC_DERIVATION = 50
    SOURCE_SUBSTRATE = 60


class TokenKind(IntEnum):
    IDENTIFIER = 10
    KEYWORD = 20
    OPERATOR = 30
    PUNCTUATION = 40
    LITERAL = 50
    STRING = 60
    NUMBER = 70
    UNKNOWN = 80


class AnnotationKind(IntEnum):
    COMMENT = 10
    DOCUMENTATION = 20
    PRAGMA_OR_DIRECTIVE = 30
    PARSE_ERROR = 40
    MISSING_SYNTAX = 50


class SyntaxKind(IntEnum):
    SYNTAX_NODE = 10
    STATEMENT = 20
    EXPRESSION = 30
    PATTERN = 40
    DECLARATION_SYNTAX = 50
    TYPE_SYNTAX = 60
    PARAMETER_SYNTAX = 70
    ARGUMENT_SYNTAX = 80
    BLOCK = 90
    LITERAL = 100
    OPERATION = 110
    ATTRIBUTE_ACCESS = 120
    MEMBER_ACCESS = 130
    SUBSCRIPT_ACCESS = 140
    INDEX_ACCESS = 150
    CALL_EXPRESSION = 160
    ASSIGNMENT = 170
    BRANCH = 180
    LOOP = 190
    RETURN = 200
    YIELD = 210
    AWAIT = 220
    RAISE_OR_PANIC_SYNTAX = 230
    IMPORT_OR_USE_SYNTAX = 240


class SyntaxFieldRole(IntEnum):
    NAME = 10
    PARAMETERS = 20
    DECORATOR = 30
    RETURNS = 40
    BODY = 50
    CONDITION = 60
    TARGET = 70
    VALUE = 80
    RECEIVER = 90
    CALLEE = 100
    ARGUMENT = 110
    KEYWORD_ARGUMENT = 120
    ITERABLE = 130
    GUARD = 140
    PATTERN = 150
    HANDLER = 160
    FINALLY_BODY = 170


class OwnerKind(IntEnum):
    SOURCE_FILE = 10
    MODULE = 20
    SCOPE = 30
    CALLABLE = 40
    CLASS_OR_TYPE = 50
    MIR_BODY = 60
    CRATE_OR_BUILD_UNIT = 70
    WORKSPACE_GLOBAL_DERIVATION = 80


class Language(IntEnum):
    COMMON = 10
    PYTHON = 20
    RUST = 30
    UNKNOWN = 40


class PathEncoding(IntEnum):
    UNIX_BYTES = 10
    MACOS_BYTES = 20
    WINDOWS_WTF8 = 30


class UpdateCandidateStrategy(IntEnum):
    ISOLATED_PATHS = 10
    GIT_STATUS_INDEX = 20
    HEAD_TREE_AND_STATUS = 30
    GENERIC_INVENTORY = 40


class UpdateWaveItemState(IntEnum):
    PENDING = 10
    CAPTURED = 20
    REMOVED = 30
    DEFERRED_SOURCE_DRIFT = 40
    FAILED = 50


class OperationalDependencyEdgeKind(IntEnum):
    SYNTAX = 10
    SEMANTIC = 20
    DERIVATION = 30
    PUBLICATION = 40


class GitHashAlgorithm(IntEnum):
    SHA1 = 10
    SHA256 = 20


class GitRepositoryKind(IntEnum):
    COMMON = 10
    LINKED_WORKTREE = 20
    SUBMODULE = 30


class GitHeadKind(IntEnum):
    SYMBOLIC = 10
    DETACHED = 20
    UNBORN = 30


class GitOperationState(IntEnum):
    CLEAN = 10
    MERGE = 20
    REBASE = 30
    CHERRY_PICK = 40
    REVERT = 50
    BISECT = 60
    APPLY = 70
    OTHER_OPERATION = 80
    UNKNOWN = 90


class GitInventoryClassification(IntEnum):
    TRACKED = 10
    UNTRACKED_NOT_IGNORED = 20
    UNTRACKED_IGNORED = 30
    TRACKED_BUT_IGNORED_PATTERN_MATCHES = 40
    EXCLUDED_BY_CODE_FABRIC_POLICY = 50
    SUBMODULE_GITLINK = 60
    NESTED_REPOSITORY = 70
    SPECIAL_FILE = 80


class InventoryInclusionState(IntEnum):
    INCLUDED = 10
    EXCLUDED_POLICY = 20
    EXCLUDED_SPECIAL_FILE = 30
    EXCLUDED_SIZE_LIMIT = 40


class InventoryFileKind(IntEnum):
    REGULAR = 10
    SYMLINK = 20
    SPECIAL = 30


class GitCandidateOrigin(IntEnum):
    INDEX_WORKTREE = 10
    HEAD_INDEX = 20
    HEAD_TREE = 30


class GitCandidateMode(IntEnum):
    STATUS = 10
    HEAD_TREE = 20


class OverlayTombstoneReason(IntEnum):
    OWNER_REPLACED_EMPTY = 10
    SOURCE_REMOVED = 20
    SUPERSEDED_GENERATION = 30


class NewlineKind(IntEnum):
    NONE = 10
    LF = 20
    CRLF = 30
    CR = 40
    MIXED = 50


class OccurrenceFamily(IntEnum):
    TOKEN = 10
    ANNOTATION = 20
    SYNTAX = 30


class ProviderObservationFamily(IntEnum):
    RUST_MIR_OWNER = 120


class RangeReconciliationStep(IntEnum):
    EXACT_RANGE_AND_KIND = 10
    EXACT_DECLARATION_NAME = 20
    SMALLEST_ENCLOSING_COMPATIBLE = 30
    SAME_START_COMPATIBLE = 40
    PROVIDER_ONLY_SYNTHETIC = 50


class RawKindDisposition(IntEnum):
    NORMALIZE = 10
    IGNORE = 20
    UNSUPPORTED = 30


class WorkspaceKind(IntEnum):
    NON_GIT_ROOT = 10
    GIT_WORKTREE = 20


class AnalysisContextKind(IntEnum):
    SOURCE = 10
    PYTHON = 20
    RUST = 30


class ValueKind(IntEnum):
    ENTITY = 10
    BOOLEAN = 20
    INTEGER = 30
    FLOAT = 40
    TEXT = 50
    BYTES = 60
    TYPE = 70


class Severity(IntEnum):
    INFO = 10
    WARNING = 20
    ERROR = 30
    FATAL = 40


class Phase(IntEnum):
    INPUT_VALIDATION = 10
    SCHEMA_BINDING = 20
    LOGICAL_PLANNING = 30
    POLICY_VALIDATION = 40
    PHYSICAL_PLANNING = 50
    EXECUTION = 60
    WRITE_VALIDATION = 70
    COMMIT = 80
    SNAPSHOT_CONSTRUCTION = 90
    SNAPSHOT_ACTIVATION = 100
    SHUTDOWN = 110


class WorkspaceLifecycle(IntEnum):
    BOOTSTRAPPING = 10
    READY = 20
    DEGRADED = 30
    DISABLED = 40
    FAILED = 50


class UpdateWaveState(IntEnum):
    COLLECTING = 10
    SNAPSHOTTING = 20
    RUNNING = 30
    PUBLISHING = 40
    COMPLETE = 50
    FAILED = 60
    SUPERSEDED = 70
    GIT_CANDIDATE_BUILDING = 80
    GIT_BASELINE_VERIFYING = 90
    CLASSIFYING = 100
    FAST_ANALYZING = 110
    FAST_VALIDATING = 120
    FAST_PUBLISHED = 130
    SEMANTIC_ANALYZING = 140
    DERIVING = 150
    VALIDATING = 160
    HOT_PUBLISHED = 170
    DURABLE_FLUSHING = 180
    DURABLE_PUBLISHED = 190
    CANCELLED = 200


class ArtifactState(IntEnum):
    BUILDING = 10
    READY = 20
    ACTIVE = 30
    EXPIRED = 40
    FAILED = 50


class WorkspaceRegistryLifecycle(IntEnum):
    REGISTERING = 10
    DISABLED = 20
    OPENING = 30
    BOOTSTRAPPING = 40
    READY = 50
    DEGRADED = 60
    DISABLING = 70
    REMOVING = 80
    REMOVED = 90
    FAILED = 100


class FactFlags(IntFlag):
    NONE = 0
    GENERATED = 1
    LOWERED = 2
    EXTERNAL = 4
    UNKNOWN_REMAINDER = 8
    PYTHON_PROFILE = 4294967296
    RUST_PROFILE = 8589934592
    COMPILER_SYNTHETIC = 281474976710656


class ProviderNodeFlags(IntFlag):
    NONE = 0


# fmt: off
ENUM_TRIPLES = MappingProxyType({
    "EVIDENCE_CERTAINTY": (
        (10, "SOURCE_EXACT", "source-exact"),
        (20, "COMPILER_EXACT", "compiler-exact"),
        (30, "STATIC_SEMANTIC", "static-semantic"),
        (40, "SOUND_MAY", "sound-may"),
        (50, "MODELLED", "modelled"),
        (60, "HEURISTIC", "heuristic"),
        (70, "UNRESOLVED", "unresolved"),
    ),
    "RESOLUTION_CLASS": (
        (10, "EXACT", "exact"),
        (20, "STATICALLY_RESOLVED", "statically-resolved"),
        (30, "SOUND_POSSIBLE", "sound-possible"),
        (40, "POSSIBLE", "possible"),
        (50, "MODELLED", "modelled"),
        (60, "HEURISTIC", "heuristic"),
        (70, "UNRESOLVED", "unresolved"),
        (80, "UNAVAILABLE", "unavailable"),
        (90, "NOT_APPLICABLE", "not-applicable"),
    ),
    "DIRECTNESS": (
        (10, "DIRECT", "direct"),
        (20, "TRANSITIVE", "transitive"),
        (30, "SUMMARY", "summary"),
        (40, "NOT_APPLICABLE", "not-applicable"),
    ),
    "COMPLETENESS": (
        (10, "COMPLETE", "complete"),
        (20, "PARTIAL", "partial"),
        (30, "INDETERMINATE", "indeterminate"),
        (40, "UNAVAILABLE", "unavailable"),
        (50, "NOT_APPLICABLE", "not-applicable"),
    ),
    "OWNER_CAPABILITY_STATE": (
        (10, "CURRENT", "current"),
        (20, "PENDING", "pending"),
        (30, "INVALIDATED", "invalidated"),
        (40, "PARTIAL", "partial"),
        (50, "UNAVAILABLE_PARSE", "unavailable-parse"),
        (60, "UNAVAILABLE_COMPILE", "unavailable-compile"),
        (70, "UNAVAILABLE_PROVIDER", "unavailable-provider"),
        (80, "UNAVAILABLE_DERIVATION", "unavailable-derivation"),
        (90, "EXCLUDED", "excluded"),
        (100, "UNSUPPORTED", "unsupported"),
        (110, "REMOVED", "removed"),
        (120, "NOT_APPLICABLE", "not-applicable"),
    ),
    "PROVIDER_RUN_STATE": (
        (10, "QUEUED", "queued"),
        (20, "RUNNING", "running"),
        (30, "SUCCEEDED", "succeeded"),
        (40, "PARTIAL", "partial"),
        (50, "FAILED", "failed"),
        (60, "TIMED_OUT", "timed-out"),
        (70, "CANCELLED", "cancelled"),
        (80, "SUPERSEDED", "superseded"),
        (90, "CRASHED", "crashed"),
        (100, "PROTOCOL_ERROR", "protocol-error"),
        (110, "STALE_RESULT", "stale-result"),
        (120, "STALE_GIT_BASELINE", "stale-git-baseline"),
    ),
    "QUERY_EXECUTION_STATE": (
        (10, "ACCEPTED", "accepted"),
        (20, "RUNNING", "running"),
        (30, "COMPLETE", "complete"),
        (40, "FAILED", "failed"),
        (50, "CANCELLED", "cancelled"),
        (60, "DEADLINE_EXCEEDED", "deadline-exceeded"),
        (70, "NOT_EXECUTED_DEPENDENCY", "not-executed-dependency"),
    ),
    "QUERY_FORM": (
        (10, "FIND_ENTITIES", "find code entities"),
        (20, "RETRIEVE_FACTS", "retrieve facts about code"),
        (30, "FOLLOW_RELATIONSHIPS", "follow code relationships"),
        (40, "FIND_PATHS", "find connecting fact paths"),
        (50, "MATCH_PATTERN", "match a code fact pattern"),
        (60, "COMBINE_RESULTS", "combine result sets"),
        (70, "SUMMARIZE_FACTS", "summarize objective facts"),
        (80, "RETRIEVE_SOURCE_CONTEXT", "retrieve source and syntax context"),
    ),
    "QUERY_AVAILABILITY_STATE": (
        (10, "AVAILABLE", "available"),
        (20, "PARTIAL", "partial"),
        (30, "UNAVAILABLE", "unavailable"),
        (40, "NOT_APPLICABLE", "not-applicable"),
    ),
    "COMPLETENESS_STATE": (
        (10, "COMPLETE", "complete"),
        (20, "PARTIAL", "partial"),
        (30, "INDETERMINATE", "indeterminate"),
        (40, "UNAVAILABLE", "unavailable"),
        (50, "NOT_APPLICABLE", "not-applicable"),
    ),
    "FRESHNESS_STATE": (
        (10, "CURRENT", "current"),
        (20, "POTENTIALLY_STALE", "potentially-stale"),
        (30, "UNAVAILABLE", "unavailable"),
    ),
    "LIMIT_STATE": (
        (10, "NOT_APPLIED", "not-applied"),
        (20, "EXPLICIT_LIMIT_REACHED", "explicit-limit-reached"),
        (30, "HARD_LIMIT_REJECTED", "hard-limit-rejected"),
    ),
    "DEPENDENCY_STATE": (
        (10, "READY", "ready"),
        (20, "FAILED_DEPENDENCY", "failed-dependency"),
        (30, "NOT_APPLICABLE", "not-applicable"),
    ),
    "DURABLE_PUBLICATION_STATE": (
        (10, "STAGING", "staging"),
        (20, "VALIDATING", "validating"),
        (30, "VALIDATED", "validated"),
        (40, "COMMITTING", "committing"),
        (50, "COMPLETE", "complete"),
        (60, "FAILED", "failed"),
        (70, "ABANDONED", "abandoned"),
    ),
    "SERVING_ACTIVATION_STATE": (
        (10, "BUILDING", "building"),
        (20, "VALIDATING", "validating"),
        (30, "READY", "ready"),
        (40, "ACTIVE", "active"),
        (50, "RETIRED", "retired"),
        (60, "FAILED", "failed"),
    ),
    "SNAPSHOT_LEASE_KIND": (
        (10, "QUERY", "query"),
        (20, "RESULT_ARTIFACT", "result-artifact"),
        (30, "RESOURCE_READ", "resource-read"),
        (40, "MAINTENANCE", "maintenance"),
    ),
    "SNAPSHOT_LEASE_STATE": (
        (10, "ACTIVE", "active"),
        (20, "RELEASING", "releasing"),
        (30, "RELEASED", "released"),
        (40, "EXPIRED", "expired"),
        (50, "ORPHANED", "orphaned"),
    ),
    "SOURCE_TRUST_STATE": (
        (10, "UNVERIFIED", "unverified"),
        (20, "VERIFYING", "verifying"),
        (30, "CURRENT", "current"),
        (40, "POTENTIALLY_STALE", "potentially-stale"),
        (50, "UNAVAILABLE", "unavailable"),
    ),
    "EVENT_STREAM_HEALTH": (
        (10, "HEALTHY", "healthy"),
        (20, "RESCAN_REQUIRED", "rescan-required"),
        (30, "DEGRADED", "degraded"),
        (40, "UNAVAILABLE", "unavailable"),
    ),
    "GIT_ACCELERATION_STATUS": (
        (10, "NOT_A_GIT_WORKTREE", "not-a-git-worktree"),
        (20, "GIT_UNAVAILABLE", "git-unavailable"),
        (30, "GIT_READY", "git-ready"),
        (40, "GIT_METADATA_DIRTY", "git-metadata-dirty"),
        (50, "GIT_SCANNING", "git-scanning"),
        (60, "GIT_OPERATION_IN_PROGRESS", "git-operation-in-progress"),
        (70, "GIT_BULK_RECONCILING", "git-bulk-reconciling"),
        (80, "GIT_DEGRADED", "git-degraded"),
    ),
    "EFFECT_KIND": (
        (10, "READ_MEMORY", "read-memory"),
        (20, "WRITE_MEMORY", "write-memory"),
        (30, "ALLOCATE_MEMORY", "allocate-memory"),
        (40, "DEALLOCATE_MEMORY", "deallocate-memory"),
        (50, "READ_FILE", "read-file"),
        (60, "WRITE_FILE", "write-file"),
        (70, "READ_NETWORK", "read-network"),
        (80, "WRITE_NETWORK", "write-network"),
        (90, "READ_DATABASE", "read-database"),
        (100, "WRITE_DATABASE", "write-database"),
        (110, "BEGIN_TRANSACTION", "begin-transaction"),
        (120, "COMMIT_TRANSACTION", "commit-transaction"),
        (130, "ROLLBACK_TRANSACTION", "rollback-transaction"),
        (140, "READ_STANDARD_INPUT", "read-standard-input"),
        (150, "WRITE_STANDARD_OUTPUT", "write-standard-output"),
        (160, "LOG_OR_TELEMETRY", "log-or-telemetry"),
        (170, "READ_ENVIRONMENT", "read-environment"),
        (180, "WRITE_ENVIRONMENT", "write-environment"),
        (190, "SPAWN_PROCESS", "spawn-process"),
        (200, "SPAWN_THREAD_OR_TASK", "spawn-thread-or-task"),
        (210, "BLOCK_THREAD", "block-thread"),
        (220, "SLEEP_OR_WAIT", "sleep-or-wait"),
        (230, "LOAD_DYNAMIC_LIBRARY", "load-dynamic-library"),
        (240, "ACQUIRE_LOCK", "acquire-lock"),
        (250, "RELEASE_LOCK", "release-lock"),
        (260, "SEND_CHANNEL", "send-channel"),
        (270, "RECEIVE_CHANNEL", "receive-channel"),
        (280, "READ_TIME", "read-time"),
        (290, "READ_RANDOMNESS", "read-randomness"),
        (300, "READ_GLOBAL_STATE", "read-global-state"),
        (310, "WRITE_GLOBAL_STATE", "write-global-state"),
        (320, "RAISE_EXCEPTION", "raise-exception"),
        (330, "PANIC_OR_ABORT", "panic-or-abort"),
        (340, "UNSAFE_OPERATION", "unsafe-operation"),
        (350, "FFI_CALL", "ffi-call"),
        (360, "DYNAMIC_CODE_EXECUTION", "dynamic-code-execution"),
        (370, "UNKNOWN_EXTERNAL_EFFECT", "unknown-external-effect"),
    ),
    "RESOURCE_KIND": (
        (10, "FILE_HANDLE", "file-handle"),
        (20, "SOCKET_OR_CONNECTION", "socket-or-connection"),
        (30, "DATABASE_CONNECTION_OR_TRANSACTION", "database-connection-or-transaction"),
        (40, "LOCK_GUARD", "lock-guard"),
        (50, "CHANNEL_ENDPOINT", "channel-endpoint"),
        (60, "PROCESS_HANDLE", "process-handle"),
        (70, "THREAD_OR_TASK_HANDLE", "thread-or-task-handle"),
        (80, "MEMORY_ALLOCATION", "memory-allocation"),
        (90, "USER_DEFINED_MODELLED_RESOURCE", "user-defined-modelled-resource"),
        (100, "UNKNOWN_RESOURCE", "unknown-resource"),
    ),
    "PROVIDER_CODE": (
        (10, "TREE_SITTER", "tree-sitter"),
        (20, "RUFF_PYTHON", "ruff-python"),
        (30, "PYREFLY_PYTHON", "pyrefly-python"),
        (40, "RUSTC_MIR", "rustc-mir"),
        (50, "CODEFABRIC_DERIVATION", "codefabric-derivation"),
        (60, "SOURCE_SUBSTRATE", "source-substrate"),
    ),
    "TOKEN_KIND": (
        (10, "IDENTIFIER", "identifier"),
        (20, "KEYWORD", "keyword"),
        (30, "OPERATOR", "operator"),
        (40, "PUNCTUATION", "punctuation"),
        (50, "LITERAL", "literal"),
        (60, "STRING", "string"),
        (70, "NUMBER", "number"),
        (80, "UNKNOWN", "unknown"),
    ),
    "ANNOTATION_KIND": (
        (10, "COMMENT", "comment"),
        (20, "DOCUMENTATION", "documentation"),
        (30, "PRAGMA_OR_DIRECTIVE", "pragma-or-directive"),
        (40, "PARSE_ERROR", "parse-error"),
        (50, "MISSING_SYNTAX", "missing-syntax"),
    ),
    "SYNTAX_KIND": (
        (10, "SYNTAX_NODE", "syntax-node"),
        (20, "STATEMENT", "statement"),
        (30, "EXPRESSION", "expression"),
        (40, "PATTERN", "pattern"),
        (50, "DECLARATION_SYNTAX", "declaration-syntax"),
        (60, "TYPE_SYNTAX", "type-syntax"),
        (70, "PARAMETER_SYNTAX", "parameter-syntax"),
        (80, "ARGUMENT_SYNTAX", "argument-syntax"),
        (90, "BLOCK", "block"),
        (100, "LITERAL", "literal"),
        (110, "OPERATION", "operation"),
        (120, "ATTRIBUTE_ACCESS", "attribute-access"),
        (130, "MEMBER_ACCESS", "member-access"),
        (140, "SUBSCRIPT_ACCESS", "subscript-access"),
        (150, "INDEX_ACCESS", "index-access"),
        (160, "CALL_EXPRESSION", "call-expression"),
        (170, "ASSIGNMENT", "assignment"),
        (180, "BRANCH", "branch"),
        (190, "LOOP", "loop"),
        (200, "RETURN", "return"),
        (210, "YIELD", "yield"),
        (220, "AWAIT", "await"),
        (230, "RAISE_OR_PANIC_SYNTAX", "raise-or-panic-syntax"),
        (240, "IMPORT_OR_USE_SYNTAX", "import-or-use-syntax"),
    ),
    "SYNTAX_FIELD_ROLE": (
        (10, "NAME", "name"),
        (20, "PARAMETERS", "parameters"),
        (30, "DECORATOR", "decorator"),
        (40, "RETURNS", "returns"),
        (50, "BODY", "body"),
        (60, "CONDITION", "condition"),
        (70, "TARGET", "target"),
        (80, "VALUE", "value"),
        (90, "RECEIVER", "receiver"),
        (100, "CALLEE", "callee"),
        (110, "ARGUMENT", "argument"),
        (120, "KEYWORD_ARGUMENT", "keyword-argument"),
        (130, "ITERABLE", "iterable"),
        (140, "GUARD", "guard"),
        (150, "PATTERN", "pattern"),
        (160, "HANDLER", "handler"),
        (170, "FINALLY_BODY", "finally-body"),
    ),
    "OWNER_KIND": (
        (10, "SOURCE_FILE", "source-file"),
        (20, "MODULE", "module"),
        (30, "SCOPE", "scope"),
        (40, "CALLABLE", "callable"),
        (50, "CLASS_OR_TYPE", "class-or-type"),
        (60, "MIR_BODY", "mir-body"),
        (70, "CRATE_OR_BUILD_UNIT", "crate-or-build-unit"),
        (80, "WORKSPACE_GLOBAL_DERIVATION", "workspace-global-derivation"),
    ),
    "LANGUAGE": (
        (10, "COMMON", "common"),
        (20, "PYTHON", "python"),
        (30, "RUST", "rust"),
        (40, "UNKNOWN", "unknown"),
    ),
    "PATH_ENCODING": (
        (10, "UNIX_BYTES", "unix-bytes"),
        (20, "MACOS_BYTES", "macos-bytes"),
        (30, "WINDOWS_WTF8", "windows-wtf8"),
    ),
    "UPDATE_CANDIDATE_STRATEGY": (
        (10, "ISOLATED_PATHS", "isolated-paths"),
        (20, "GIT_STATUS_INDEX", "git-status-index"),
        (30, "HEAD_TREE_AND_STATUS", "head-tree-and-status"),
        (40, "GENERIC_INVENTORY", "generic-inventory"),
    ),
    "UPDATE_WAVE_ITEM_STATE": (
        (10, "PENDING", "pending"),
        (20, "CAPTURED", "captured"),
        (30, "REMOVED", "removed"),
        (40, "DEFERRED_SOURCE_DRIFT", "deferred-source-drift"),
        (50, "FAILED", "failed"),
    ),
    "OPERATIONAL_DEPENDENCY_EDGE_KIND": (
        (10, "SYNTAX", "syntax"),
        (20, "SEMANTIC", "semantic"),
        (30, "DERIVATION", "derivation"),
        (40, "PUBLICATION", "publication"),
    ),
    "GIT_HASH_ALGORITHM": (
        (10, "SHA1", "sha1"),
        (20, "SHA256", "sha256"),
    ),
    "GIT_REPOSITORY_KIND": (
        (10, "COMMON", "common"),
        (20, "LINKED_WORKTREE", "linked-worktree"),
        (30, "SUBMODULE", "submodule"),
    ),
    "GIT_HEAD_KIND": (
        (10, "SYMBOLIC", "symbolic"),
        (20, "DETACHED", "detached"),
        (30, "UNBORN", "unborn"),
    ),
    "GIT_OPERATION_STATE": (
        (10, "CLEAN", "clean"),
        (20, "MERGE", "merge"),
        (30, "REBASE", "rebase"),
        (40, "CHERRY_PICK", "cherry-pick"),
        (50, "REVERT", "revert"),
        (60, "BISECT", "bisect"),
        (70, "APPLY", "apply"),
        (80, "OTHER_OPERATION", "other-operation"),
        (90, "UNKNOWN", "unknown"),
    ),
    "GIT_INVENTORY_CLASSIFICATION": (
        (10, "TRACKED", "tracked"),
        (20, "UNTRACKED_NOT_IGNORED", "untracked-not-ignored"),
        (30, "UNTRACKED_IGNORED", "untracked-ignored"),
        (40, "TRACKED_BUT_IGNORED_PATTERN_MATCHES", "tracked-but-ignored-pattern-matches"),
        (50, "EXCLUDED_BY_CODE_FABRIC_POLICY", "excluded-by-code-fabric-policy"),
        (60, "SUBMODULE_GITLINK", "submodule-gitlink"),
        (70, "NESTED_REPOSITORY", "nested-repository"),
        (80, "SPECIAL_FILE", "special-file"),
    ),
    "INVENTORY_INCLUSION_STATE": (
        (10, "INCLUDED", "included"),
        (20, "EXCLUDED_POLICY", "excluded-policy"),
        (30, "EXCLUDED_SPECIAL_FILE", "excluded-special-file"),
        (40, "EXCLUDED_SIZE_LIMIT", "excluded-size-limit"),
    ),
    "INVENTORY_FILE_KIND": (
        (10, "REGULAR", "regular"),
        (20, "SYMLINK", "symlink"),
        (30, "SPECIAL", "special"),
    ),
    "GIT_CANDIDATE_ORIGIN": (
        (10, "INDEX_WORKTREE", "index-worktree"),
        (20, "HEAD_INDEX", "head-index"),
        (30, "HEAD_TREE", "head-tree"),
    ),
    "GIT_CANDIDATE_MODE": (
        (10, "STATUS", "status"),
        (20, "HEAD_TREE", "head-tree"),
    ),
    "OVERLAY_TOMBSTONE_REASON": (
        (10, "OWNER_REPLACED_EMPTY", "owner-replaced-empty"),
        (20, "SOURCE_REMOVED", "source-removed"),
        (30, "SUPERSEDED_GENERATION", "superseded-generation"),
    ),
    "NEWLINE_KIND": (
        (10, "NONE", "none"),
        (20, "LF", "lf"),
        (30, "CRLF", "crlf"),
        (40, "CR", "cr"),
        (50, "MIXED", "mixed"),
    ),
    "OCCURRENCE_FAMILY": (
        (10, "TOKEN", "token"),
        (20, "ANNOTATION", "annotation"),
        (30, "SYNTAX", "syntax"),
    ),
    "PROVIDER_OBSERVATION_FAMILY": (
        (120, "RUST_MIR_OWNER", "rust-mir-owner"),
    ),
    "RANGE_RECONCILIATION_STEP": (
        (10, "EXACT_RANGE_AND_KIND", "exact-range-and-kind"),
        (20, "EXACT_DECLARATION_NAME", "exact-declaration-name"),
        (30, "SMALLEST_ENCLOSING_COMPATIBLE", "smallest-enclosing-compatible"),
        (40, "SAME_START_COMPATIBLE", "same-start-compatible"),
        (50, "PROVIDER_ONLY_SYNTHETIC", "provider-only-synthetic"),
    ),
    "RAW_KIND_DISPOSITION": (
        (10, "NORMALIZE", "normalize"),
        (20, "IGNORE", "ignore"),
        (30, "UNSUPPORTED", "unsupported"),
    ),
    "WORKSPACE_KIND": (
        (10, "NON_GIT_ROOT", "non-git-root"),
        (20, "GIT_WORKTREE", "git-worktree"),
    ),
    "ANALYSIS_CONTEXT_KIND": (
        (10, "SOURCE", "source"),
        (20, "PYTHON", "python"),
        (30, "RUST", "rust"),
    ),
    "VALUE_KIND": (
        (10, "ENTITY", "entity"),
        (20, "BOOLEAN", "boolean"),
        (30, "INTEGER", "integer"),
        (40, "FLOAT", "float"),
        (50, "TEXT", "text"),
        (60, "BYTES", "bytes"),
        (70, "TYPE", "type"),
    ),
    "SEVERITY": (
        (10, "INFO", "info"),
        (20, "WARNING", "warning"),
        (30, "ERROR", "error"),
        (40, "FATAL", "fatal"),
    ),
    "PHASE": (
        (10, "INPUT_VALIDATION", "input-validation"),
        (20, "SCHEMA_BINDING", "schema-binding"),
        (30, "LOGICAL_PLANNING", "logical-planning"),
        (40, "POLICY_VALIDATION", "policy-validation"),
        (50, "PHYSICAL_PLANNING", "physical-planning"),
        (60, "EXECUTION", "execution"),
        (70, "WRITE_VALIDATION", "write-validation"),
        (80, "COMMIT", "commit"),
        (90, "SNAPSHOT_CONSTRUCTION", "snapshot-construction"),
        (100, "SNAPSHOT_ACTIVATION", "snapshot-activation"),
        (110, "SHUTDOWN", "shutdown"),
    ),
    "WORKSPACE_LIFECYCLE": (
        (10, "BOOTSTRAPPING", "bootstrapping"),
        (20, "READY", "ready"),
        (30, "DEGRADED", "degraded"),
        (40, "DISABLED", "disabled"),
        (50, "FAILED", "failed"),
    ),
    "UPDATE_WAVE_STATE": (
        (10, "COLLECTING", "collecting"),
        (20, "SNAPSHOTTING", "snapshotting"),
        (30, "RUNNING", "running"),
        (40, "PUBLISHING", "publishing"),
        (50, "COMPLETE", "complete"),
        (60, "FAILED", "failed"),
        (70, "SUPERSEDED", "superseded"),
        (80, "GIT_CANDIDATE_BUILDING", "git-candidate-building"),
        (90, "GIT_BASELINE_VERIFYING", "git-baseline-verifying"),
        (100, "CLASSIFYING", "classifying"),
        (110, "FAST_ANALYZING", "fast-analyzing"),
        (120, "FAST_VALIDATING", "fast-validating"),
        (130, "FAST_PUBLISHED", "fast-published"),
        (140, "SEMANTIC_ANALYZING", "semantic-analyzing"),
        (150, "DERIVING", "deriving"),
        (160, "VALIDATING", "validating"),
        (170, "HOT_PUBLISHED", "hot-published"),
        (180, "DURABLE_FLUSHING", "durable-flushing"),
        (190, "DURABLE_PUBLISHED", "durable-published"),
        (200, "CANCELLED", "cancelled"),
    ),
    "ARTIFACT_STATE": (
        (10, "BUILDING", "building"),
        (20, "READY", "ready"),
        (30, "ACTIVE", "active"),
        (40, "EXPIRED", "expired"),
        (50, "FAILED", "failed"),
    ),
    "WORKSPACE_REGISTRY_LIFECYCLE": (
        (10, "REGISTERING", "registering"),
        (20, "DISABLED", "disabled"),
        (30, "OPENING", "opening"),
        (40, "BOOTSTRAPPING", "bootstrapping"),
        (50, "READY", "ready"),
        (60, "DEGRADED", "degraded"),
        (70, "DISABLING", "disabling"),
        (80, "REMOVING", "removing"),
        (90, "REMOVED", "removed"),
        (100, "FAILED", "failed"),
    ),
})


PHRASES = MappingProxyType({
    "Q50_SOURCE_FILES": MappingProxyType({"owner_section": 50, "canonical_text": "source files", "accepted_aliases": tuple(["source documents"]), "plan_node_kind": "find-entities", "output_role": "entity-set"}),
    "Q51_SYNTAX_NODES": MappingProxyType({"owner_section": 51, "canonical_text": "syntax nodes", "accepted_aliases": tuple(["syntax occurrences"]), "plan_node_kind": "find-entities", "output_role": "entity-set"}),
    "Q52_SEMANTIC_SYMBOLS": MappingProxyType({"owner_section": 52, "canonical_text": "semantic symbols", "accepted_aliases": tuple(["bound symbols"]), "plan_node_kind": "find-entities", "output_role": "entity-set"}),
    "Q53_MODULE_DEPENDENCIES": MappingProxyType({"owner_section": 53, "canonical_text": "module dependencies", "accepted_aliases": tuple(["module imports"]), "plan_node_kind": "follow-relationships", "output_role": "fact-set"}),
    "Q54_SEMANTIC_TYPES": MappingProxyType({"owner_section": 54, "canonical_text": "semantic types", "accepted_aliases": tuple(["computed types"]), "plan_node_kind": "find-entities", "output_role": "entity-set"}),
    "Q55_OBJECT_MEMBERS": MappingProxyType({"owner_section": 55, "canonical_text": "object members", "accepted_aliases": tuple(["declared members"]), "plan_node_kind": "follow-relationships", "output_role": "fact-set"}),
    "Q56_CALLABLE_CONTRACTS": MappingProxyType({"owner_section": 56, "canonical_text": "callable contracts", "accepted_aliases": tuple(["callable signatures"]), "plan_node_kind": "retrieve-facts", "output_role": "fact-set"}),
    "Q57_CALL_TARGETS": MappingProxyType({"owner_section": 57, "canonical_text": "call targets", "accepted_aliases": tuple(["dispatch targets"]), "plan_node_kind": "follow-relationships", "output_role": "fact-set"}),
    "Q58_CONTROL_FLOW": MappingProxyType({"owner_section": 58, "canonical_text": "control flow", "accepted_aliases": tuple(["control paths"]), "plan_node_kind": "find-paths", "output_role": "path-set"}),
    "Q59_DATA_FLOW": MappingProxyType({"owner_section": 59, "canonical_text": "data flow", "accepted_aliases": tuple(["definition use flow"]), "plan_node_kind": "follow-relationships", "output_role": "fact-set"}),
    "Q60_MEMORY_ALIASES": MappingProxyType({"owner_section": 60, "canonical_text": "memory aliases", "accepted_aliases": tuple(["points to relations"]), "plan_node_kind": "follow-relationships", "output_role": "fact-set"}),
    "Q61_PROGRAM_POINT_STATE": MappingProxyType({"owner_section": 61, "canonical_text": "program point state", "accepted_aliases": tuple(["state at program point"]), "plan_node_kind": "retrieve-facts", "output_role": "fact-set"}),
    "Q62_EFFECTS": MappingProxyType({"owner_section": 62, "canonical_text": "effects", "accepted_aliases": tuple(["observable effects"]), "plan_node_kind": "retrieve-facts", "output_role": "fact-set"}),
    "Q63_EXCEPTIONAL_FLOW": MappingProxyType({"owner_section": 63, "canonical_text": "exceptional flow", "accepted_aliases": tuple(["exception paths"]), "plan_node_kind": "find-paths", "output_role": "path-set"}),
    "Q64_RESOURCE_LIFETIMES": MappingProxyType({"owner_section": 64, "canonical_text": "resource lifetimes", "accepted_aliases": tuple(["resource actions"]), "plan_node_kind": "retrieve-facts", "output_role": "fact-set"}),
    "Q65_CONCURRENCY_EVENTS": MappingProxyType({"owner_section": 65, "canonical_text": "concurrency events", "accepted_aliases": tuple(["task ordering events"]), "plan_node_kind": "find-paths", "output_role": "path-set"}),
    "Q66_CLOSURE_CAPTURES": MappingProxyType({"owner_section": 66, "canonical_text": "closure captures", "accepted_aliases": tuple(["captured symbols"]), "plan_node_kind": "follow-relationships", "output_role": "fact-set"}),
    "Q67_GENERATED_ORIGINS": MappingProxyType({"owner_section": 67, "canonical_text": "generated origins", "accepted_aliases": tuple(["lowered origins"]), "plan_node_kind": "follow-relationships", "output_role": "fact-set"}),
    "Q68_GRAPH_METRICS": MappingProxyType({"owner_section": 68, "canonical_text": "graph metrics", "accepted_aliases": tuple(["objective graph measures"]), "plan_node_kind": "summarize-facts", "output_role": "scalar-summary"}),
    "Q69_CALLABLE_SUMMARIES": MappingProxyType({"owner_section": 69, "canonical_text": "callable summaries", "accepted_aliases": tuple(["interprocedural summaries"]), "plan_node_kind": "summarize-facts", "output_role": "group-set"}),
    "Q70_EXPLICIT_UNKNOWNS": MappingProxyType({"owner_section": 70, "canonical_text": "explicit unknowns", "accepted_aliases": tuple(["unresolved facts"]), "plan_node_kind": "retrieve-facts", "output_role": "coverage-proof"}),
    "Q71_PYTHON_BINDINGS": MappingProxyType({"owner_section": 71, "canonical_text": "Python bindings", "accepted_aliases": tuple(["Python scopes"]), "plan_node_kind": "find-entities", "output_role": "entity-set"}),
    "Q72_PYTHON_TYPES": MappingProxyType({"owner_section": 72, "canonical_text": "Python types", "accepted_aliases": tuple(["Python inferred types"]), "plan_node_kind": "find-entities", "output_role": "entity-set"}),
    "Q73_PYTHON_OBJECT_MEMBERS": MappingProxyType({"owner_section": 73, "canonical_text": "Python object members", "accepted_aliases": tuple(["Python descriptors"]), "plan_node_kind": "follow-relationships", "output_role": "fact-set"}),
    "Q74_PYTHON_CALL_TARGETS": MappingProxyType({"owner_section": 74, "canonical_text": "Python call targets", "accepted_aliases": tuple(["Python dispatch targets"]), "plan_node_kind": "follow-relationships", "output_role": "fact-set"}),
    "Q75_PYTHON_DYNAMIC_SEMANTICS": MappingProxyType({"owner_section": 75, "canonical_text": "Python dynamic semantics", "accepted_aliases": tuple(["Python dynamic operations"]), "plan_node_kind": "retrieve-facts", "output_role": "fact-set"}),
    "Q76_PYTHON_DECORATORS": MappingProxyType({"owner_section": 76, "canonical_text": "Python decorators", "accepted_aliases": tuple(["Python decorated entities"]), "plan_node_kind": "follow-relationships", "output_role": "fact-set"}),
    "Q77_PYTHON_PATTERN_MATCHING": MappingProxyType({"owner_section": 77, "canonical_text": "Python pattern matching", "accepted_aliases": tuple(["Python match cases"]), "plan_node_kind": "match-pattern", "output_role": "binding-table"}),
    "Q78_PYTHON_COMPREHENSIONS": MappingProxyType({"owner_section": 78, "canonical_text": "Python comprehensions", "accepted_aliases": tuple(["Python comprehension scopes"]), "plan_node_kind": "find-entities", "output_role": "entity-set"}),
    "Q79_PYTHON_CONTEXT_MANAGERS": MappingProxyType({"owner_section": 79, "canonical_text": "Python context managers", "accepted_aliases": tuple(["Python with statements"]), "plan_node_kind": "retrieve-facts", "output_role": "fact-set"}),
    "Q80_PYTHON_ASYNC_GENERATORS": MappingProxyType({"owner_section": 80, "canonical_text": "Python async generators", "accepted_aliases": tuple(["Python coroutine generators"]), "plan_node_kind": "find-entities", "output_role": "entity-set"}),
    "Q81_RUST_SEMANTIC_ITEMS": MappingProxyType({"owner_section": 81, "canonical_text": "Rust semantic items", "accepted_aliases": tuple(["Rust source items"]), "plan_node_kind": "find-entities", "output_role": "entity-set"}),
    "Q82_RUST_GENERICS": MappingProxyType({"owner_section": 82, "canonical_text": "Rust generics", "accepted_aliases": tuple(["Rust generic parameters"]), "plan_node_kind": "find-entities", "output_role": "entity-set"}),
    "Q83_RUST_TYPE_ADJUSTMENTS": MappingProxyType({"owner_section": 83, "canonical_text": "Rust type adjustments", "accepted_aliases": tuple(["Rust coercions"]), "plan_node_kind": "follow-relationships", "output_role": "fact-set"}),
    "Q84_RUST_MIR_STRUCTURE": MappingProxyType({"owner_section": 84, "canonical_text": "Rust MIR structure", "accepted_aliases": tuple(["Rust MIR bodies"]), "plan_node_kind": "find-entities", "output_role": "entity-set"}),
    "Q85_RUST_PLACE_PROJECTIONS": MappingProxyType({"owner_section": 85, "canonical_text": "Rust place projections", "accepted_aliases": tuple(["Rust MIR places"]), "plan_node_kind": "follow-relationships", "output_role": "fact-set"}),
    "Q86_RUST_MIR_TRANSITIONS": MappingProxyType({"owner_section": 86, "canonical_text": "Rust MIR transitions", "accepted_aliases": tuple(["Rust MIR state changes"]), "plan_node_kind": "follow-relationships", "output_role": "fact-set"}),
    "Q87_RUST_OWNERSHIP_LOANS": MappingProxyType({"owner_section": 87, "canonical_text": "Rust ownership loans", "accepted_aliases": tuple(["Rust borrow loans"]), "plan_node_kind": "follow-relationships", "output_role": "fact-set"}),
    "Q88_RUST_EXECUTABLE_INSTANCES": MappingProxyType({"owner_section": 88, "canonical_text": "Rust executable instances", "accepted_aliases": tuple(["Rust monomorphic calls"]), "plan_node_kind": "follow-relationships", "output_role": "fact-set"}),
    "Q89_RUST_TRAIT_DISPATCH": MappingProxyType({"owner_section": 89, "canonical_text": "Rust trait dispatch", "accepted_aliases": tuple(["Rust implementation dispatch"]), "plan_node_kind": "follow-relationships", "output_role": "fact-set"}),
    "Q90_RUST_MACRO_EXPANSIONS": MappingProxyType({"owner_section": 90, "canonical_text": "Rust macro expansions", "accepted_aliases": tuple(["Rust expanded origins"]), "plan_node_kind": "follow-relationships", "output_role": "fact-set"}),
    "Q91_RUST_DROP_BEHAVIOR": MappingProxyType({"owner_section": 91, "canonical_text": "Rust drop behavior", "accepted_aliases": tuple(["Rust destruction effects"]), "plan_node_kind": "retrieve-facts", "output_role": "fact-set"}),
    "Q92_RUST_COROUTINE_LOWERING": MappingProxyType({"owner_section": 92, "canonical_text": "Rust coroutine lowering", "accepted_aliases": tuple(["Rust async lowering"]), "plan_node_kind": "follow-relationships", "output_role": "fact-set"}),
    "Q93_RUST_UNSAFE_FFI": MappingProxyType({"owner_section": 93, "canonical_text": "Rust unsafe FFI", "accepted_aliases": tuple(["Rust foreign operations"]), "plan_node_kind": "retrieve-facts", "output_role": "fact-set"}),
    "Q94_RUST_COMPILE_TIME_VALUES": MappingProxyType({"owner_section": 94, "canonical_text": "Rust compile time values", "accepted_aliases": tuple(["Rust constants and statics"]), "plan_node_kind": "retrieve-facts", "output_role": "fact-set"}),
})


REGISTRY_IDS = MappingProxyType({
    "entity_kinds": (
        "WORKSPACE",
        "SOURCE_FILE",
        "SOURCE_SPAN",
        "TOKEN",
        "SYNTAX_NODE",
        "PARSE_ERROR",
        "MODULE",
        "SCOPE",
        "SYMBOL",
        "DECLARATION",
        "REFERENCE",
        "CALLABLE",
        "CALL_SITE",
        "SEMANTIC_TYPE",
        "CFG_BLOCK",
        "VALUE",
        "MEMORY_LOCATION",
        "TASK",
        "THREAD",
        "EFFECT",
        "RESOURCE",
        "UNKNOWN",
        "ARTIFACT",
        "SNAPSHOT",
        "IDENTIFIER_TOKEN",
        "KEYWORD_TOKEN",
        "OPERATOR_TOKEN",
        "PUNCTUATION_TOKEN",
        "LITERAL_TOKEN",
        "STRING_TOKEN",
        "NUMBER_TOKEN",
        "COMMENT",
        "DOCUMENTATION",
        "PRAGMA_OR_DIRECTIVE",
        "MISSING_SYNTAX",
        "STATEMENT",
        "EXPRESSION",
        "PATTERN",
        "DECLARATION_SYNTAX",
        "TYPE_SYNTAX",
        "PARAMETER_SYNTAX",
        "ARGUMENT_SYNTAX",
        "BLOCK",
        "LITERAL",
        "OPERATION",
        "ATTRIBUTE_ACCESS",
        "MEMBER_ACCESS",
        "SUBSCRIPT_ACCESS",
        "INDEX_ACCESS",
        "CALL_EXPRESSION",
        "ASSIGNMENT",
        "BRANCH",
        "LOOP",
        "RETURN",
        "YIELD",
        "AWAIT",
        "RAISE_OR_PANIC_SYNTAX",
        "IMPORT_OR_USE_SYNTAX",
    ),
    "relation_kinds": (
        "CONTAINS",
        "AST_CHILD",
        "DECLARES",
        "REFERS_TO",
        "CALLS",
        "HAS_TYPE",
        "CFG_NORMAL",
        "DEF_USE",
        "POINTS_TO",
        "HAS_EFFECT",
        "USES_RESOURCE",
        "PROGRAM_ORDER_BEFORE",
        "SYNCHRONIZES_WITH_EXACT",
        "CONTAINS_SPAN",
        "TOKEN_OF",
        "LEXICALLY_PRECEDES",
        "DOCUMENTS",
        "DIRECTIVE_APPLIES_TO",
    ),
    "property_kinds": (
        "NAME",
        "QUALIFIED_NAME",
        "RAW_PATH",
        "CONTENT_DIGEST",
        "SPAN_START_BYTE",
        "SPAN_END_BYTE",
        "TYPE_REF",
        "VISIBILITY",
        "LANGUAGE",
        "CATEGORICAL_KIND",
    ),
    "fact_kinds": (
        "ENTITY_EXISTENCE",
        "RELATION",
        "PROPERTY",
    ),
    "unknowns": (
        "UNKNOWN_SYMBOL",
        "UNKNOWN_TYPE",
        "UNKNOWN_MODULE",
        "UNKNOWN_MEMBER",
        "UNKNOWN_CALL_TARGET",
        "UNKNOWN_EXTERNAL_IMPLEMENTATION",
        "UNKNOWN_VALUE",
        "UNKNOWN_MEMORY_LOCATION",
        "UNKNOWN_EFFECT",
        "UNKNOWN_RESOURCE",
        "UNKNOWN_FFI_TARGET",
        "UNKNOWN_CONCURRENCY_TARGET",
        "DYNAMIC_LANGUAGE_OPEN_WORLD",
        "EXTERNAL_BODY_NOT_INDEXED",
        "PROVIDER_UNAVAILABLE",
        "ANALYSIS_WIDENED",
        "REFLECTION_OR_CODE_GENERATION",
        "FFI_UNRESOLVED",
        "UNSUPPORTED_CONSTRUCT",
        "CONFLICTING_EXACT_EVIDENCE",
        "SOURCE_INVALID",
        "PROVEN_DOES_NOT_ALIAS_UNDER_PROFILE",
        "PROVEN_NO_PATH_WITHIN_PROJECTION_AND_BOUNDARY",
        "PROVEN_NOT_SUBTYPE_IN_CLOSED_TYPE_UNIVERSE",
        "PROVEN_NO_RESOLVED_MEMBER_IN_CLOSED_MEMBER_SET",
    ),
    "projections": (
        "SYNTAX_TREE_V1",
        "SYMBOL_BINDING_V1",
        "TYPE_GRAPH_V1",
        "CALL_EXACT_V1",
        "CALL_SOUND_V1",
        "CFG_NORMAL_V1",
        "CFG_FULL_V1",
        "DATAFLOW_V1",
        "ALIAS_V1",
        "OWNERSHIP_V1",
        "EFFECT_V1",
        "DEPENDENCY_V1",
        "CONCURRENCY_V1",
    ),
    "summaries": (
        "CALLABLE_SUMMARY_BALANCED_V1",
    ),
    "capabilities": (
        "SOURCE_BYTES",
        "SOURCE_INVENTORY",
        "TOKENS",
        "CST",
        "TYPED_AST",
        "SCOPES_BINDINGS",
        "IMPORT_RESOLUTION",
        "DECLARED_TYPES",
        "COMPUTED_TYPES",
        "MEMBER_RESOLUTION",
        "CALL_TARGETS",
        "RUST_MIR",
        "BORROW_LOANS",
        "CFG",
        "DOMINANCE",
        "CONTROL_DEPENDENCE",
        "DEF_USE",
        "LIVENESS",
        "POINTS_TO_ALIAS",
        "EFFECTS",
        "CONCURRENCY",
        "CALLABLE_SUMMARIES",
    ),
    "providers": (
        "tree-sitter",
        "ruff-python",
        "pyrefly-python",
        "rustc-mir",
        "codefabric-derivation",
        "source-substrate",
    ),
    "provider_normalizations": (
        "tree-sitter-python-syntax-v1",
        "tree-sitter-rust-syntax-v1",
        "ruff-python-syntax-v1",
    ),
    "provider_resource_profiles": (
        "in-process-syntax-standard",
        "sidecar-semantic-standard",
        "compiler-semantic-standard",
        "derivation-standard",
    ),
    "public_errors": (
        "INCOMPATIBLE_MAJOR",
        "UNSUPPORTED_MINOR",
        "BUNDLE_DIGEST_MISMATCH",
        "WORKSPACE_NOT_AUTHORIZED",
        "PATH_OUTSIDE_AUTHORIZED_ROOT",
        "SOURCE_ACCESS_DENIED",
        "BLOCKED_PATH_COLLISION",
        "FRESHNESS_DEADLINE_EXCEEDED",
        "CAPABILITY_UNAVAILABLE",
        "NEGATIVE_PROOF_INDETERMINATE",
        "SOURCE_SNAPSHOT_MISMATCH",
        "PROVIDER_PROTOCOL_ERROR",
        "SANDBOX_UNAVAILABLE",
        "QUERY_HARD_LIMIT_EXCEEDED",
        "ENTITY_AMBIGUOUS",
        "SEMANTIC_PHRASE_AMBIGUOUS",
        "SEMANTIC_PHRASE_UNRECOGNIZED",
        "CURRENT_POINTER_CONFLICT",
        "ID_COLLISION",
        "OVERLAY_GENERATION_CONFLICT",
        "CREDENTIAL_REPLAY_DETECTED",
        "IDEMPOTENCY_CONFLICT",
        "RESUME_WINDOW_EXPIRED",
        "RESULT_TOO_LARGE_FOR_HOST",
        "ARTIFACT_ID_COLLISION",
        "RESOURCE_EXPIRED",
        "STATE_TRANSITION_VIOLATION",
        "INTERNAL_INVARIANT_VIOLATION",
        "INVALID_REQUEST_SCHEMA",
        "CONTEXT_NOT_INDEXED",
        "COMPOSITE_SNAPSHOT_UNSUPPORTED",
        "RESOURCE_LIMIT_REJECTED",
        "CANCELLED",
        "ADAPTER_INPUT_NOT_JSON",
        "ADAPTER_INPUT_LIMIT",
        "ADAPTER_INPUT_VALIDATION",
        "ADAPTER_OUTPUT_CONTRACT",
        "UNSUPPORTED_BINARY",
        "UNSUPPORTED_CONTENT",
        "CURRENT_FACTS_UNAVAILABLE",
        "DEFAULT_CONTEXT_UNAVAILABLE",
        "WORKSPACE_BOOTSTRAPPING",
        "FACT_FAMILY_UNAVAILABLE",
        "SNAPSHOT_FRESHNESS_MISMATCH",
        "QUERY_LOST_DAEMON_RESTART",
        "COMPARISON_DOMAIN_MISMATCH",
        "SCHEMA_MISMATCH",
        "TABLE_SET_MISMATCH",
        "ROW_MISMATCH",
        "CAPABILITY_MISMATCH",
        "SNAPSHOT_METADATA_MISMATCH",
        "ID_COLLISION_DETECTED",
        "COMPARATOR_ERROR",
        "PUBLICATION_REFERENTIAL_INTEGRITY",
        "REQUIRED_FEATURE_UNSUPPORTED",
        "SCHEMA_DIGEST_MISMATCH",
        "TOOLCHAIN_MISMATCH",
        "MODEL_PACK_INCOMPATIBLE",
        "PLATFORM_UNSUPPORTED",
        "DAEMON_UNAVAILABLE",
        "CONTRACT_MISMATCH",
        "INTERNAL",
    ),
    "derivations": (
        "SYNTAX_TREE_V1",
    ),
    "phrases": (
        "Q50_SOURCE_FILES",
        "Q51_SYNTAX_NODES",
        "Q52_SEMANTIC_SYMBOLS",
        "Q53_MODULE_DEPENDENCIES",
        "Q54_SEMANTIC_TYPES",
        "Q55_OBJECT_MEMBERS",
        "Q56_CALLABLE_CONTRACTS",
        "Q57_CALL_TARGETS",
        "Q58_CONTROL_FLOW",
        "Q59_DATA_FLOW",
        "Q60_MEMORY_ALIASES",
        "Q61_PROGRAM_POINT_STATE",
        "Q62_EFFECTS",
        "Q63_EXCEPTIONAL_FLOW",
        "Q64_RESOURCE_LIFETIMES",
        "Q65_CONCURRENCY_EVENTS",
        "Q66_CLOSURE_CAPTURES",
        "Q67_GENERATED_ORIGINS",
        "Q68_GRAPH_METRICS",
        "Q69_CALLABLE_SUMMARIES",
        "Q70_EXPLICIT_UNKNOWNS",
        "Q71_PYTHON_BINDINGS",
        "Q72_PYTHON_TYPES",
        "Q73_PYTHON_OBJECT_MEMBERS",
        "Q74_PYTHON_CALL_TARGETS",
        "Q75_PYTHON_DYNAMIC_SEMANTICS",
        "Q76_PYTHON_DECORATORS",
        "Q77_PYTHON_PATTERN_MATCHING",
        "Q78_PYTHON_COMPREHENSIONS",
        "Q79_PYTHON_CONTEXT_MANAGERS",
        "Q80_PYTHON_ASYNC_GENERATORS",
        "Q81_RUST_SEMANTIC_ITEMS",
        "Q82_RUST_GENERICS",
        "Q83_RUST_TYPE_ADJUSTMENTS",
        "Q84_RUST_MIR_STRUCTURE",
        "Q85_RUST_PLACE_PROJECTIONS",
        "Q86_RUST_MIR_TRANSITIONS",
        "Q87_RUST_OWNERSHIP_LOANS",
        "Q88_RUST_EXECUTABLE_INSTANCES",
        "Q89_RUST_TRAIT_DISPATCH",
        "Q90_RUST_MACRO_EXPANSIONS",
        "Q91_RUST_DROP_BEHAVIOR",
        "Q92_RUST_COROUTINE_LOWERING",
        "Q93_RUST_UNSAFE_FFI",
        "Q94_RUST_COMPILE_TIME_VALUES",
    ),
})
# fmt: on
