# @generated by codefabric-model from codefabric.query.form-contract 1.0 (b3:773cc5003e6756548f7ee25725b9a3d0212529d9c67efb345039e0a17ca89377); do not edit.
from typing import Final, Literal

QUERY_FORM_CONTRACT_ID: Final = "codefabric.query.form-contract"
QUERY_FORM_CONTRACT_VERSION: Final = "1.0"
QUERY_FORM_CONTRACT_DIGEST: Final = (
    "b3:773cc5003e6756548f7ee25725b9a3d0212529d9c67efb345039e0a17ca89377"
)
QUERY_FORMS: Final = (
    "find code entities",
    "retrieve facts about code",
    "follow code relationships",
    "find connecting fact paths",
    "match a code fact pattern",
    "combine result sets",
    "summarize objective facts",
    "retrieve source and syntax context",
)
type QueryForm = Literal[
    "find code entities",
    "retrieve facts about code",
    "follow code relationships",
    "find connecting fact paths",
    "match a code fact pattern",
    "combine result sets",
    "summarize objective facts",
    "retrieve source and syntax context",
]
QUERY_FORM_NODE_KINDS: Final = {
    "find code entities": "find-entities",
    "retrieve facts about code": "retrieve-facts",
    "follow code relationships": "follow-relationships",
    "find connecting fact paths": "find-paths",
    "match a code fact pattern": "match-pattern",
    "combine result sets": "combine-results",
    "summarize objective facts": "summarize-facts",
    "retrieve source and syntax context": "retrieve-source-context",
}
