//! Closed Contract IR for generated storage and public schema surfaces.

use std::collections::{BTreeMap, BTreeSet};
use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use super::models::ArtifactHeader;

/// Logical type names fixed by Data Fabric §7.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum LogicalType {
    Id16,
    Hash32,
    Code16,
    Code32,
    Bucket16,
    Int16,
    Int32,
    Int64,
    Float64,
    Boolean,
    Utf8,
    Binary,
    TimestampUtc,
    IdList,
    StringMap,
}

/// Durable write behavior for one table.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum DurableMutationClass {
    StaticDimension,
    CurrentSingleton,
    OwnerReplacedFact,
    PublicationAppend,
    DerivedOwnerReplaced,
    GlobalDerivedReplacement,
}

/// Hot-overlay mutation behavior for one table.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum OverlayMutationPolicy {
    OwnerReplace,
    PrimaryKeyUpsert,
    FullTableReplace,
    BaseImmutable,
    NotApplicable,
}

/// Query-visible materialization role for one table.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum MaterializationRole {
    DurableEffective,
    BundleDimension,
    QueryTimeDerived,
    OperationalProjection,
}

/// One closed Arrow field declaration.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ColumnContract {
    pub name: String,
    pub logical_type: LogicalType,
    pub nullable: bool,
    #[serde(default)]
    pub semantic_type: Option<String>,
    #[serde(default)]
    pub foreign_key: Option<String>,
    #[serde(default)]
    pub hidden_operational: bool,
}

/// One `TableSpec` source record.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TableContract {
    pub table_code: i16,
    pub name: String,
    pub family: String,
    pub grain: String,
    pub schema_version: String,
    pub columns: Vec<ColumnContract>,
    pub primary_key: Vec<String>,
    pub partition_columns: Vec<String>,
    pub zorder_columns: Vec<String>,
    pub durable_mutation: DurableMutationClass,
    pub overlay_mutation: OverlayMutationPolicy,
    pub materialization_role: MaterializationRole,
    pub dependencies: Vec<i16>,
    pub required_for_publication: bool,
}

/// `SQLite` affinity names accepted by the operational DDL generator.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum SqliteType {
    Integer,
    Real,
    Text,
    Blob,
}

/// One operational-store column declaration.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct OperationalColumnContract {
    pub name: String,
    pub sqlite_type: SqliteType,
    pub nullable: bool,
}

/// One generated `SQLite` table declaration.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct OperationalTableContract {
    pub name: String,
    pub columns: Vec<OperationalColumnContract>,
    pub primary_key: Vec<String>,
    #[serde(default)]
    pub unique: Vec<Vec<String>>,
}

/// Closed public-schema families generated by the schema compiler.
#[derive(Clone, Copy, Debug, Deserialize, Eq, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum PublicSchemaKind {
    AnalysisContext,
    ServingSnapshot,
    PublicSnapshotMetadata,
    SourceContext,
    PublicStatus,
    CpgSemanticQueryRequest,
    CpgSemanticQueryResponse,
    PlanSpec,
}

/// One public schema output and its exact governed identity.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct PublicSchemaContract {
    pub schema_kind: PublicSchemaKind,
    pub artifact_id: String,
    pub path: PathBuf,
    pub title: String,
}

/// Single typed authority for WP09 schema generation.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SchemaContractIr {
    #[serde(flatten)]
    pub header: ArtifactHeader,
    pub schema_version: u16,
    pub ontology_version: String,
    pub compatibility_mode: String,
    pub owner_bucket_count: u16,
    pub tables: Vec<TableContract>,
    pub operational_tables: Vec<OperationalTableContract>,
    pub public_schemas: Vec<PublicSchemaContract>,
}

impl SchemaContractIr {
    /// Validate all cross-record identities before any output allocation.
    #[allow(clippy::too_many_lines)] // One pass keeps cross-table IR validation atomic.
    pub fn validate(&self) -> Result<(), String> {
        if self.schema_version != 1 || self.owner_bucket_count != 256 {
            return Err("schema_version must be 1 and owner_bucket_count must be 256".into());
        }
        let mut table_codes = BTreeSet::new();
        let mut table_names = BTreeSet::new();
        for table in &self.tables {
            if !table_codes.insert(table.table_code) || !table_names.insert(&table.name) {
                return Err(format!("duplicate table identity: {}", table.name));
            }
            let columns = table
                .columns
                .iter()
                .map(|column| column.name.as_str())
                .collect::<BTreeSet<_>>();
            if columns.len() != table.columns.len() {
                return Err(format!("duplicate column in {}", table.name));
            }
            for key in table
                .primary_key
                .iter()
                .chain(&table.partition_columns)
                .chain(&table.zorder_columns)
            {
                if !columns.contains(key.as_str()) {
                    return Err(format!("{} references unknown column {key}", table.name));
                }
            }
            if table.columns.iter().any(|column| {
                matches!(column.logical_type, LogicalType::Utf8) && column.name.contains("json")
            }) {
                return Err(format!(
                    "{} contains a prohibited JSON/EAV text column",
                    table.name
                ));
            }
            match table.materialization_role {
                MaterializationRole::BundleDimension
                    if table.durable_mutation != DurableMutationClass::StaticDimension
                        || table.overlay_mutation != OverlayMutationPolicy::BaseImmutable =>
                {
                    return Err(format!(
                        "{} has an illegal bundle-dimension policy cross-product",
                        table.name
                    ));
                }
                MaterializationRole::QueryTimeDerived
                    if table.overlay_mutation != OverlayMutationPolicy::NotApplicable =>
                {
                    return Err(format!(
                        "{} gives a query-time-derived surface an overlay mutation",
                        table.name
                    ));
                }
                MaterializationRole::OperationalProjection
                    if table.required_for_publication || !table.name.ends_with("tombstone") =>
                {
                    return Err(format!(
                        "{} exposes an operational projection as an effective fact",
                        table.name
                    ));
                }
                MaterializationRole::DurableEffective if table.name.ends_with("tombstone") => {
                    return Err(format!(
                        "{} exposes an overlay tombstone as a durable fact",
                        table.name
                    ));
                }
                _ => {}
            }
        }
        if self.tables.len() != 17 {
            return Err(format!(
                "expected 17 TableSpecs, found {}",
                self.tables.len()
            ));
        }
        let names_by_code = self
            .tables
            .iter()
            .map(|table| (table.table_code, table.name.as_str()))
            .collect::<BTreeMap<_, _>>();
        for table in &self.tables {
            for dependency in &table.dependencies {
                if !names_by_code.contains_key(dependency) {
                    return Err(format!(
                        "{} has unknown dependency {dependency}",
                        table.name
                    ));
                }
            }
        }
        let mut operational_names = BTreeSet::new();
        for table in &self.operational_tables {
            if !operational_names.insert(table.name.as_str()) {
                return Err(format!("duplicate operational table: {}", table.name));
            }
            let columns = table
                .columns
                .iter()
                .map(|column| column.name.as_str())
                .collect::<BTreeSet<_>>();
            for key in table
                .primary_key
                .iter()
                .chain(table.unique.iter().flatten())
            {
                if !columns.contains(key.as_str()) {
                    return Err(format!(
                        "{} references unknown SQL column {key}",
                        table.name
                    ));
                }
            }
        }
        let expected_operational_names = BTreeSet::from([
            "active_snapshot",
            "audit_event",
            "common_repository_state",
            "credential_metadata",
            "git_operation_run",
            "git_state_vector",
            "hot_overlay_manifest",
            "nested_root_exclusion",
            "provider_run",
            "repository_registration",
            "result_artifact_lease",
            "serving_snapshot_manifest",
            "snapshot_lease",
            "update_wave",
            "update_wave_item",
            "workspace_generation",
            "workspace_registration",
            "worktree_registration",
            "worktree_state",
        ]);
        if operational_names != expected_operational_names {
            return Err("operational table census differs from the closed AC-G-27 set".into());
        }
        let schemas = self
            .public_schemas
            .iter()
            .map(|schema| schema.schema_kind)
            .collect::<BTreeSet<_>>();
        if schemas.len() != 8 || schemas.len() != self.public_schemas.len() {
            return Err("the public-schema catalog must contain each of eight kinds once".into());
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn authority() -> SchemaContractIr {
        serde_json::from_str(include_str!(
            "../../contracts/schema/schema-contract-ir.json"
        ))
        .unwrap()
    }

    #[test]
    fn schema_contract_ir_is_closed_and_complete() {
        authority().validate().unwrap();
    }

    #[test]
    fn wp09_negative_zero_state() {
        let mut duplicate = authority();
        duplicate.tables[1].table_code = duplicate.tables[0].table_code;
        assert!(
            duplicate
                .validate()
                .unwrap_err()
                .contains("duplicate table")
        );

        let mut json_blob = authority();
        json_blob.tables[0].columns[4].name = "opaque_json".to_owned();
        json_blob.tables[0].columns[4].logical_type = LogicalType::Utf8;
        assert!(json_blob.validate().unwrap_err().contains("JSON/EAV"));

        let mut illegal_axis = authority();
        illegal_axis.tables[10].overlay_mutation = OverlayMutationPolicy::OwnerReplace;
        assert!(
            illegal_axis
                .validate()
                .unwrap_err()
                .contains("bundle-dimension")
        );

        let source = include_str!("../../contracts/schema/schema-contract-ir.json").replacen(
            "\"logical_type\":\"utf8\"",
            "\"logical_type\":\"utf8_view\"",
            1,
        );
        assert!(serde_json::from_str::<SchemaContractIr>(&source).is_err());
    }
}
