//! Validated runtime model for one source or semantic analysis context.

use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::identity::{
    CbefField, CbefRecord, CbefValue, IdentityDomain, IdentityError, SOURCE_CONTEXT_ID,
    StringNormalization, decode_public_id, derive_identity, encode_public_id,
};

/// Closed analysis context kinds accepted by the public contract.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum AnalysisContextKind {
    Source,
    Python,
    Rust,
}

impl AnalysisContextKind {
    const fn canonical_name(self) -> &'static str {
        match self {
            Self::Source => "source",
            Self::Python => "python",
            Self::Rust => "rust",
        }
    }
}

/// Public `AnalysisContext` document generated by validated construction.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct AnalysisContext {
    pub workspace_id: String,
    pub analysis_context_id: String,
    pub context_kind: AnalysisContextKind,
    pub context_fingerprint: String,
    pub provider_bundle_version: String,
    pub compiler_or_language_version: String,
    pub configuration_manifest_uri: Option<String>,
    pub active: bool,
}

/// Analysis-context validation and identity failures.
#[derive(Clone, Debug, Error, Eq, PartialEq)]
pub enum AnalysisContextError {
    #[error("invalid analysis-context identity: {0}")]
    Identity(#[from] IdentityError),
    #[error("analysis-context versions must be non-empty")]
    EmptyVersion,
    #[error("configuration_manifest_uri is not a valid URI-reference")]
    InvalidUriReference,
    #[error("analysis-context ID or fingerprint does not match its semantic fields")]
    IdentityMismatch,
    #[error("context:source is reserved for the source context")]
    SourceContextMismatch,
}

impl AnalysisContext {
    /// Build a context and derive its ID and fingerprint from one CBEF-v1 record.
    ///
    /// # Errors
    ///
    /// Returns an error for invalid public workspace IDs, empty versions, or URI references.
    pub fn new(
        workspace_id: &str,
        context_kind: AnalysisContextKind,
        provider_bundle_version: impl Into<String>,
        compiler_or_language_version: impl Into<String>,
        configuration_manifest_uri: Option<String>,
        active: bool,
    ) -> Result<Self, AnalysisContextError> {
        let workspace_bytes = decode_public_id(IdentityDomain::Workspace, None, workspace_id)?;
        let provider_bundle_version = provider_bundle_version.into();
        let compiler_or_language_version = compiler_or_language_version.into();
        validate_fields(
            &provider_bundle_version,
            &compiler_or_language_version,
            configuration_manifest_uri.as_deref(),
        )?;
        let context_fingerprint = semantic_fingerprint(
            context_kind,
            &provider_bundle_version,
            &compiler_or_language_version,
            configuration_manifest_uri.as_deref(),
        );
        let identity = context_identity(workspace_bytes, context_kind, context_fingerprint)?;
        let context_id = if context_kind == AnalysisContextKind::Source {
            SOURCE_CONTEXT_ID
        } else {
            identity.id
        };
        let analysis_context_id = if context_kind == AnalysisContextKind::Source {
            "context:source".to_owned()
        } else {
            encode_public_id(IdentityDomain::AnalysisContext, None, context_id)?
        };
        Ok(Self {
            workspace_id: workspace_id.to_owned(),
            analysis_context_id,
            context_kind,
            context_fingerprint: format!("b3:{}", lower_hex(&context_fingerprint)),
            provider_bundle_version,
            compiler_or_language_version,
            configuration_manifest_uri,
            active,
        })
    }

    /// Re-validate a deserialized document against the same identity recipe.
    ///
    /// # Errors
    ///
    /// Returns an error when any identity, fingerprint, or semantic field is inconsistent.
    pub fn validate(&self) -> Result<(), AnalysisContextError> {
        let rebuilt = Self::new(
            &self.workspace_id,
            self.context_kind,
            self.provider_bundle_version.clone(),
            self.compiler_or_language_version.clone(),
            self.configuration_manifest_uri.clone(),
            self.active,
        )?;
        if self.analysis_context_id != rebuilt.analysis_context_id
            || self.context_fingerprint != rebuilt.context_fingerprint
        {
            return Err(AnalysisContextError::IdentityMismatch);
        }
        if (self.analysis_context_id == "context:source")
            != (self.context_kind == AnalysisContextKind::Source)
        {
            return Err(AnalysisContextError::SourceContextMismatch);
        }
        Ok(())
    }

    /// Decode the validated public fingerprint to its fixed-width storage form.
    ///
    /// # Errors
    ///
    /// Returns an error if a caller mutated the public fingerprint into a non-canonical value.
    pub fn fingerprint_bytes(&self) -> Result<[u8; 32], AnalysisContextError> {
        let payload = self
            .context_fingerprint
            .strip_prefix("b3:")
            .ok_or(AnalysisContextError::IdentityMismatch)?;
        if payload.len() != 64
            || !payload
                .bytes()
                .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
        {
            return Err(AnalysisContextError::IdentityMismatch);
        }
        let mut output = [0_u8; 32];
        for (index, slot) in output.iter_mut().enumerate() {
            *slot = u8::from_str_radix(&payload[index * 2..index * 2 + 2], 16)
                .map_err(|_| AnalysisContextError::IdentityMismatch)?;
        }
        Ok(output)
    }

    /// Parse a JSON document through the closed model and validate its identities.
    ///
    /// # Errors
    ///
    /// Returns strict JSON/model errors or semantic validation failures.
    pub fn from_json(bytes: &[u8]) -> Result<Self, AnalysisContextJsonError> {
        let value = crate::contracts::jcs::decode_strict(bytes)?;
        let document: Self = serde_json::from_value(value)?;
        document.validate()?;
        Ok(document)
    }
}

/// Strict JSON boundary failure for [`AnalysisContext::from_json`].
#[derive(Debug, Error)]
pub enum AnalysisContextJsonError {
    #[error("invalid strict analysis-context JSON: {0}")]
    Canonical(#[from] crate::contracts::jcs::CanonicalJsonError),
    #[error("invalid analysis-context JSON: {0}")]
    Json(#[from] serde_json::Error),
    #[error(transparent)]
    Contract(#[from] AnalysisContextError),
}

fn validate_fields(
    provider_bundle_version: &str,
    compiler_or_language_version: &str,
    configuration_manifest_uri: Option<&str>,
) -> Result<(), AnalysisContextError> {
    if provider_bundle_version.is_empty() || compiler_or_language_version.is_empty() {
        return Err(AnalysisContextError::EmptyVersion);
    }
    if configuration_manifest_uri.is_some_and(|value| {
        value.chars().any(char::is_whitespace)
            || value.chars().any(char::is_control)
            || value.contains('\\')
    }) {
        return Err(AnalysisContextError::InvalidUriReference);
    }
    Ok(())
}

fn context_identity(
    workspace_id: [u8; 16],
    context_kind: AnalysisContextKind,
    environment_digest: [u8; 32],
) -> Result<crate::identity::DerivedIdentity, IdentityError> {
    derive_identity(&CbefRecord {
        domain: IdentityDomain::AnalysisContext,
        fields: vec![
            CbefField {
                tag: 1,
                value: CbefValue::Id(workspace_id),
            },
            CbefField {
                tag: 2,
                value: CbefValue::Utf8 {
                    value: context_kind.canonical_name().to_owned(),
                    normalization: StringNormalization::AsciiLower,
                },
            },
            CbefField {
                tag: 3,
                value: CbefValue::Digest(environment_digest),
            },
        ],
    })
}

fn semantic_fingerprint(
    context_kind: AnalysisContextKind,
    provider_bundle_version: &str,
    compiler_or_language_version: &str,
    configuration_manifest_uri: Option<&str>,
) -> [u8; 32] {
    let semantic_manifest = serde_json::json!({
        "context_kind": context_kind.canonical_name(),
        "provider_bundle_version": provider_bundle_version,
        "compiler_or_language_version": compiler_or_language_version,
        "configuration_manifest_uri": configuration_manifest_uri,
    });
    let bytes = crate::contracts::jcs::canonicalize_value(&semantic_manifest)
        .expect("the closed analysis-context manifest is always canonicalizable");
    crate::integrity::digest_bytes(&bytes)
}

fn lower_hex(bytes: &[u8]) -> String {
    use std::fmt::Write as _;

    let mut output = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        write!(output, "{byte:02x}").expect("writing to String is infallible");
    }
    output
}

#[cfg(test)]
mod tests {
    use super::*;

    fn workspace_id() -> String {
        encode_public_id(IdentityDomain::Workspace, None, [7; 16]).unwrap()
    }

    #[test]
    fn source_context_uses_the_reserved_symbolic_id() {
        let context = AnalysisContext::new(
            &workspace_id(),
            AnalysisContextKind::Source,
            "providers-1",
            "source-1",
            None,
            true,
        )
        .unwrap();
        assert_eq!(context.analysis_context_id, "context:source");
        assert!(context.context_fingerprint.starts_with("b3:"));
        context.validate().unwrap();
    }

    #[test]
    fn semantic_context_round_trips_strict_json_and_rejects_drift() {
        let context = AnalysisContext::new(
            &workspace_id(),
            AnalysisContextKind::Python,
            "providers-1",
            "3.14.7",
            Some("configs/python.json".to_owned()),
            true,
        )
        .unwrap();
        let bytes = serde_json::to_vec(&context).unwrap();
        assert_eq!(AnalysisContext::from_json(&bytes).unwrap(), context);

        let changed = AnalysisContext::new(
            &workspace_id(),
            AnalysisContextKind::Python,
            "providers-1",
            "3.15",
            Some("configs/python.json".to_owned()),
            true,
        )
        .unwrap();
        assert_ne!(changed.context_fingerprint, context.context_fingerprint);
        assert_ne!(changed.analysis_context_id, context.analysis_context_id);

        let mut drifted: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
        drifted["compiler_or_language_version"] = serde_json::json!("3.15");
        assert!(AnalysisContext::from_json(&serde_json::to_vec(&drifted).unwrap()).is_err());
        drifted["unknown"] = serde_json::json!(true);
        assert!(AnalysisContext::from_json(&serde_json::to_vec(&drifted).unwrap()).is_err());
        assert!(AnalysisContext::from_json(br#"{"active":true,"active":false}"#).is_err());
    }

    #[test]
    fn public_schema_and_runtime_model_expose_the_same_fields() {
        let schema: serde_json::Value = serde_json::from_slice(include_bytes!(
            "../contracts/schema/analysis-context.schema.json"
        ))
        .unwrap();
        let schema_fields = schema["properties"]
            .as_object()
            .unwrap()
            .keys()
            .cloned()
            .collect::<std::collections::BTreeSet<_>>();
        let model = AnalysisContext::new(
            &workspace_id(),
            AnalysisContextKind::Rust,
            "providers-1",
            "1.95.0",
            None,
            false,
        )
        .unwrap();
        let model_fields = serde_json::to_value(model)
            .unwrap()
            .as_object()
            .unwrap()
            .keys()
            .cloned()
            .collect::<std::collections::BTreeSet<_>>();
        assert_eq!(schema_fields, model_fields);
    }
}
