//! Validated runtime model for one source or semantic analysis context.

use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::identity::{
    CbefField, CbefRecord, CbefValue, IdentityDomain, IdentityError, SOURCE_CONTEXT_ID,
    StringNormalization, decode_public_id, derive_identity, encode_public_id,
};
/// Closed analysis context kinds accepted by the public contract.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum AnalysisContextKind {
    Source,
    Python,
    Rust,
}

impl AnalysisContextKind {
    const fn canonical_name(self) -> &'static str {
        match self {
            Self::Source => "source",
            Self::Python => "python",
            Self::Rust => "rust",
        }
    }
}

/// Public `AnalysisContext` document generated by validated construction.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct AnalysisContext {
    pub workspace_id: String,
    pub analysis_context_id: String,
    pub context_kind: AnalysisContextKind,
    pub context_fingerprint: String,
    pub provider_bundle_version: String,
    pub compiler_or_language_version: String,
    pub configuration_manifest_uri: Option<String>,
    pub active: bool,
}

/// Lane-neutral input supplied to a language-specific context-discovery adapter.
///
/// Source paths remain raw bytes. Discovery adapters may inspect only this immutable,
/// generation-pinned inventory and must return application-owned candidates.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AnalysisContextDiscoveryRequest {
    pub workspace_id: String,
    pub source_generation: u64,
    pub source_paths: Vec<Vec<u8>>,
}

/// Application-owned candidate emitted by a language-specific discovery adapter.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AnalysisContextCandidate {
    pub context_kind: AnalysisContextKind,
    pub provider_bundle_version: String,
    pub compiler_or_language_version: String,
    pub configuration_manifest_uri: Option<String>,
    /// Complete canonical-manifest fingerprint for lane implementations that have one.
    pub manifest_fingerprint: Option<[u8; 32]>,
    pub active: bool,
}

/// Shared discovery port implemented independently by the Python and Rust lanes.
///
/// Provider-library values cannot cross this boundary: implementations return the closed
/// [`AnalysisContextCandidate`] DTO and the application derives every canonical identity.
pub trait AnalysisContextDiscoveryPort {
    type Error;

    /// Discover lane-owned candidates from one immutable source inventory.
    ///
    /// # Errors
    ///
    /// Returns the lane implementation's bounded discovery failure.
    fn discover(
        &self,
        request: &AnalysisContextDiscoveryRequest,
    ) -> Result<Vec<AnalysisContextCandidate>, Self::Error>;
}

/// Analysis-context validation and identity failures.
#[derive(Clone, Debug, Error, Eq, PartialEq)]
pub enum AnalysisContextError {
    #[error("invalid analysis-context identity: {0}")]
    Identity(#[from] IdentityError),
    #[error("analysis-context versions must be non-empty")]
    EmptyVersion,
    #[error("configuration_manifest_uri is not a valid URI-reference")]
    InvalidUriReference,
    #[error("analysis-context ID or fingerprint does not match its semantic fields")]
    IdentityMismatch,
    #[error("context:source is reserved for the source context")]
    SourceContextMismatch,
    #[error("semantic context discovery cannot emit the reserved source context")]
    DiscoveredSourceContext,
    #[error("semantic context discovery emitted a duplicate canonical context")]
    DuplicateDiscoveredContext,
}

/// Materialize and deterministically order application-owned discovery candidates.
///
/// # Errors
///
/// Rejects source-context candidates, invalid candidate fields, or duplicate canonical
/// contexts. Language adapters therefore cannot choose or bypass canonical context identity.
pub fn materialize_discovered_contexts(
    request: &AnalysisContextDiscoveryRequest,
    candidates: Vec<AnalysisContextCandidate>,
) -> Result<Vec<AnalysisContext>, AnalysisContextError> {
    let mut contexts = candidates
        .into_iter()
        .map(|candidate| {
            if candidate.context_kind == AnalysisContextKind::Source {
                return Err(AnalysisContextError::DiscoveredSourceContext);
            }
            if let Some(fingerprint) = candidate.manifest_fingerprint {
                AnalysisContext::new_from_manifest_fingerprint(
                    &request.workspace_id,
                    candidate.context_kind,
                    candidate.provider_bundle_version,
                    candidate.compiler_or_language_version,
                    fingerprint,
                    candidate.active,
                )
            } else {
                AnalysisContext::new(
                    &request.workspace_id,
                    candidate.context_kind,
                    candidate.provider_bundle_version,
                    candidate.compiler_or_language_version,
                    candidate.configuration_manifest_uri,
                    candidate.active,
                )
            }
        })
        .collect::<Result<Vec<_>, _>>()?;
    contexts.sort_by(|left, right| left.analysis_context_id.cmp(&right.analysis_context_id));
    if contexts
        .windows(2)
        .any(|pair| pair[0].analysis_context_id == pair[1].analysis_context_id)
    {
        return Err(AnalysisContextError::DuplicateDiscoveredContext);
    }
    Ok(contexts)
}

impl AnalysisContext {
    /// Build a context and derive its ID and fingerprint from one CBEF-v1 record.
    ///
    /// # Errors
    ///
    /// Returns an error for invalid public workspace IDs, empty versions, or URI references.
    pub fn new(
        workspace_id: &str,
        context_kind: AnalysisContextKind,
        provider_bundle_version: impl Into<String>,
        compiler_or_language_version: impl Into<String>,
        configuration_manifest_uri: Option<String>,
        active: bool,
    ) -> Result<Self, AnalysisContextError> {
        let workspace_bytes = decode_public_id(IdentityDomain::Workspace, None, workspace_id)?;
        let provider_bundle_version = provider_bundle_version.into();
        let compiler_or_language_version = compiler_or_language_version.into();
        validate_fields(
            &provider_bundle_version,
            &compiler_or_language_version,
            configuration_manifest_uri.as_deref(),
        )?;
        let context_fingerprint = semantic_fingerprint(
            context_kind,
            &provider_bundle_version,
            &compiler_or_language_version,
            configuration_manifest_uri.as_deref(),
        );
        let identity = context_identity(workspace_bytes, context_kind, context_fingerprint)?;
        let context_id = if context_kind == AnalysisContextKind::Source {
            SOURCE_CONTEXT_ID
        } else {
            identity.id
        };
        let analysis_context_id = if context_kind == AnalysisContextKind::Source {
            "context:source".to_owned()
        } else {
            encode_public_id(IdentityDomain::AnalysisContext, None, context_id)?
        };
        Ok(Self {
            workspace_id: workspace_id.to_owned(),
            analysis_context_id,
            context_kind,
            context_fingerprint: format!("b3:{}", lower_hex(&context_fingerprint)),
            provider_bundle_version,
            compiler_or_language_version,
            configuration_manifest_uri,
            active,
        })
    }

    /// Build a semantic context whose identity commits to a complete canonical manifest.
    ///
    /// The caller owns the manifest schema and canonicalization. This shared boundary accepts
    /// only the resulting 256-bit fingerprint so provider-library values never enter canonical
    /// identity. The content-addressed manifest URI makes the identity recipe explicit on the
    /// public document and allows [`Self::validate`] to distinguish it from the legacy summary
    /// recipe used by source and pre-semantic contexts.
    ///
    /// # Errors
    ///
    /// Returns an error for a source context, malformed workspace ID, empty versions, or an
    /// invalid manifest URI.
    pub fn new_from_manifest_fingerprint(
        workspace_id: &str,
        context_kind: AnalysisContextKind,
        provider_bundle_version: impl Into<String>,
        compiler_or_language_version: impl Into<String>,
        manifest_fingerprint: [u8; 32],
        active: bool,
    ) -> Result<Self, AnalysisContextError> {
        if context_kind == AnalysisContextKind::Source {
            return Err(AnalysisContextError::SourceContextMismatch);
        }
        let workspace_bytes = decode_public_id(IdentityDomain::Workspace, None, workspace_id)?;
        let provider_bundle_version = provider_bundle_version.into();
        let compiler_or_language_version = compiler_or_language_version.into();
        let fingerprint = lower_hex(&manifest_fingerprint);
        let configuration_manifest_uri = Some(format!("codefabric-context:b3:{fingerprint}"));
        validate_fields(
            &provider_bundle_version,
            &compiler_or_language_version,
            configuration_manifest_uri.as_deref(),
        )?;
        let identity = context_identity(workspace_bytes, context_kind, manifest_fingerprint)?;
        Ok(Self {
            workspace_id: workspace_id.to_owned(),
            analysis_context_id: encode_public_id(
                IdentityDomain::AnalysisContext,
                None,
                identity.id,
            )?,
            context_kind,
            context_fingerprint: format!("b3:{fingerprint}"),
            provider_bundle_version,
            compiler_or_language_version,
            configuration_manifest_uri,
            active,
        })
    }

    /// Re-validate a deserialized document against the same identity recipe.
    ///
    /// # Errors
    ///
    /// Returns an error when any identity, fingerprint, or semantic field is inconsistent.
    pub fn validate(&self) -> Result<(), AnalysisContextError> {
        if let Some(manifest_fingerprint) = self
            .configuration_manifest_uri
            .as_deref()
            .and_then(|uri| uri.strip_prefix("codefabric-context:b3:"))
        {
            let fingerprint = self.fingerprint_bytes()?;
            if manifest_fingerprint != lower_hex(&fingerprint) {
                return Err(AnalysisContextError::IdentityMismatch);
            }
            validate_fields(
                &self.provider_bundle_version,
                &self.compiler_or_language_version,
                self.configuration_manifest_uri.as_deref(),
            )?;
            let workspace = decode_public_id(IdentityDomain::Workspace, None, &self.workspace_id)?;
            let identity = context_identity(workspace, self.context_kind, fingerprint)?;
            let expected = encode_public_id(IdentityDomain::AnalysisContext, None, identity.id)?;
            if self.context_kind == AnalysisContextKind::Source
                || self.analysis_context_id != expected
            {
                return Err(AnalysisContextError::IdentityMismatch);
            }
            return Ok(());
        }
        let rebuilt = Self::new(
            &self.workspace_id,
            self.context_kind,
            self.provider_bundle_version.clone(),
            self.compiler_or_language_version.clone(),
            self.configuration_manifest_uri.clone(),
            self.active,
        )?;
        if self.analysis_context_id != rebuilt.analysis_context_id
            || self.context_fingerprint != rebuilt.context_fingerprint
        {
            return Err(AnalysisContextError::IdentityMismatch);
        }
        if (self.analysis_context_id == "context:source")
            != (self.context_kind == AnalysisContextKind::Source)
        {
            return Err(AnalysisContextError::SourceContextMismatch);
        }
        Ok(())
    }

    /// Decode the validated public fingerprint to its fixed-width storage form.
    ///
    /// # Errors
    ///
    /// Returns an error if a caller mutated the public fingerprint into a non-canonical value.
    pub fn fingerprint_bytes(&self) -> Result<[u8; 32], AnalysisContextError> {
        let payload = self
            .context_fingerprint
            .strip_prefix("b3:")
            .ok_or(AnalysisContextError::IdentityMismatch)?;
        if payload.len() != 64
            || !payload
                .bytes()
                .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
        {
            return Err(AnalysisContextError::IdentityMismatch);
        }
        let mut output = [0_u8; 32];
        for (index, slot) in output.iter_mut().enumerate() {
            *slot = u8::from_str_radix(&payload[index * 2..index * 2 + 2], 16)
                .map_err(|_| AnalysisContextError::IdentityMismatch)?;
        }
        Ok(output)
    }

    /// Parse a JSON document through the closed model and validate its identities.
    ///
    /// # Errors
    ///
    /// Returns strict JSON/model errors or semantic validation failures.
    pub fn from_json(bytes: &[u8]) -> Result<Self, AnalysisContextJsonError> {
        let value = crate::contracts::jcs::decode_strict(bytes)?;
        let document: Self = serde_json::from_value(value)?;
        document.validate()?;
        Ok(document)
    }
}

/// Strict JSON boundary failure for [`AnalysisContext::from_json`].
#[derive(Debug, Error)]
pub enum AnalysisContextJsonError {
    #[error("invalid strict analysis-context JSON: {0}")]
    Canonical(#[from] crate::contracts::jcs::CanonicalJsonError),
    #[error("invalid analysis-context JSON: {0}")]
    Json(#[from] serde_json::Error),
    #[error(transparent)]
    Contract(#[from] AnalysisContextError),
}

fn validate_fields(
    provider_bundle_version: &str,
    compiler_or_language_version: &str,
    configuration_manifest_uri: Option<&str>,
) -> Result<(), AnalysisContextError> {
    if provider_bundle_version.is_empty() || compiler_or_language_version.is_empty() {
        return Err(AnalysisContextError::EmptyVersion);
    }
    if configuration_manifest_uri.is_some_and(|value| {
        value.chars().any(char::is_whitespace)
            || value.chars().any(char::is_control)
            || value.contains('\\')
    }) {
        return Err(AnalysisContextError::InvalidUriReference);
    }
    Ok(())
}

fn context_identity(
    workspace_id: [u8; 16],
    context_kind: AnalysisContextKind,
    environment_digest: [u8; 32],
) -> Result<crate::identity::DerivedIdentity, IdentityError> {
    derive_identity(&CbefRecord {
        domain: IdentityDomain::AnalysisContext,
        fields: vec![
            CbefField {
                tag: 1,
                value: CbefValue::Id(workspace_id),
            },
            CbefField {
                tag: 2,
                value: CbefValue::Utf8 {
                    value: context_kind.canonical_name().to_owned(),
                    normalization: StringNormalization::AsciiLower,
                },
            },
            CbefField {
                tag: 3,
                value: CbefValue::Digest(environment_digest),
            },
        ],
    })
}

fn semantic_fingerprint(
    context_kind: AnalysisContextKind,
    provider_bundle_version: &str,
    compiler_or_language_version: &str,
    configuration_manifest_uri: Option<&str>,
) -> [u8; 32] {
    let semantic_manifest = serde_json::json!({
        "context_kind": context_kind.canonical_name(),
        "provider_bundle_version": provider_bundle_version,
        "compiler_or_language_version": compiler_or_language_version,
        "configuration_manifest_uri": configuration_manifest_uri,
    });
    let bytes = crate::contracts::jcs::canonicalize_value(&semantic_manifest)
        .expect("the closed analysis-context manifest is always canonicalizable");
    crate::integrity::digest_bytes(&bytes)
}

fn lower_hex(bytes: &[u8]) -> String {
    use std::fmt::Write as _;

    let mut output = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        write!(output, "{byte:02x}").expect("writing to String is infallible");
    }
    output
}

#[cfg(test)]
mod tests {
    use super::*;

    fn workspace_id() -> String {
        encode_public_id(IdentityDomain::Workspace, None, [7; 16]).unwrap()
    }

    #[test]
    fn source_context_uses_the_reserved_symbolic_id() {
        let context = AnalysisContext::new(
            &workspace_id(),
            AnalysisContextKind::Source,
            "providers-1",
            "source-1",
            None,
            true,
        )
        .unwrap();
        assert_eq!(context.analysis_context_id, "context:source");
        assert!(context.context_fingerprint.starts_with("b3:"));
        context.validate().unwrap();
    }

    #[test]
    fn semantic_context_round_trips_strict_json_and_rejects_drift() {
        let context = AnalysisContext::new(
            &workspace_id(),
            AnalysisContextKind::Python,
            "providers-1",
            "3.14.7",
            Some("configs/python.json".to_owned()),
            true,
        )
        .unwrap();
        let bytes = serde_json::to_vec(&context).unwrap();
        assert_eq!(AnalysisContext::from_json(&bytes).unwrap(), context);

        let changed = AnalysisContext::new(
            &workspace_id(),
            AnalysisContextKind::Python,
            "providers-1",
            "3.15",
            Some("configs/python.json".to_owned()),
            true,
        )
        .unwrap();
        assert_ne!(changed.context_fingerprint, context.context_fingerprint);
        assert_ne!(changed.analysis_context_id, context.analysis_context_id);

        let mut drifted: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
        drifted["compiler_or_language_version"] = serde_json::json!("3.15");
        assert!(AnalysisContext::from_json(&serde_json::to_vec(&drifted).unwrap()).is_err());
        drifted["unknown"] = serde_json::json!(true);
        assert!(AnalysisContext::from_json(&serde_json::to_vec(&drifted).unwrap()).is_err());
        assert!(AnalysisContext::from_json(br#"{"active":true,"active":false}"#).is_err());
    }

    #[test]
    fn public_schema_and_runtime_model_expose_the_same_fields() {
        let schema: serde_json::Value = serde_json::from_slice(include_bytes!(
            "../contracts/schema/analysis-context.schema.json"
        ))
        .unwrap();
        let schema_fields = schema["properties"]
            .as_object()
            .unwrap()
            .keys()
            .cloned()
            .collect::<std::collections::BTreeSet<_>>();
        let model = AnalysisContext::new(
            &workspace_id(),
            AnalysisContextKind::Rust,
            "providers-1",
            "1.95.0",
            None,
            false,
        )
        .unwrap();
        let model_fields = serde_json::to_value(model)
            .unwrap()
            .as_object()
            .unwrap()
            .keys()
            .cloned()
            .collect::<std::collections::BTreeSet<_>>();
        assert_eq!(schema_fields, model_fields);
    }

    #[test]
    fn lane_neutral_discovery_materializes_only_application_owned_contexts() {
        struct FixtureDiscovery;

        impl AnalysisContextDiscoveryPort for FixtureDiscovery {
            type Error = std::convert::Infallible;

            fn discover(
                &self,
                _request: &AnalysisContextDiscoveryRequest,
            ) -> Result<Vec<AnalysisContextCandidate>, Self::Error> {
                Ok(vec![
                    AnalysisContextCandidate {
                        context_kind: AnalysisContextKind::Rust,
                        provider_bundle_version: "rustc-provider-1".to_owned(),
                        compiler_or_language_version: "1.95.0".to_owned(),
                        configuration_manifest_uri: Some("contexts/rust.json".to_owned()),
                        manifest_fingerprint: None,
                        active: true,
                    },
                    AnalysisContextCandidate {
                        context_kind: AnalysisContextKind::Python,
                        provider_bundle_version: "pyrefly-provider-1".to_owned(),
                        compiler_or_language_version: "3.14.7".to_owned(),
                        configuration_manifest_uri: Some("contexts/python.json".to_owned()),
                        manifest_fingerprint: None,
                        active: true,
                    },
                ])
            }
        }

        let request = AnalysisContextDiscoveryRequest {
            workspace_id: workspace_id(),
            source_generation: 7,
            source_paths: vec![b"src/lib.rs".to_vec(), b"src/app.py".to_vec()],
        };
        let candidates = FixtureDiscovery.discover(&request).unwrap();
        let first = materialize_discovered_contexts(&request, candidates.clone()).unwrap();
        let second = materialize_discovered_contexts(&request, candidates).unwrap();
        assert_eq!(first, second);
        assert_eq!(first.len(), 2);
        assert!(first.iter().all(|context| context.validate().is_ok()));
        assert!(first.windows(2).all(|pair| {
            pair[0].analysis_context_id.as_bytes() < pair[1].analysis_context_id.as_bytes()
        }));
    }

    #[test]
    fn semantic_context_kind_is_closed_by_the_application_owned_type() {
        assert_eq!(AnalysisContextKind::Python.canonical_name(), "python");
        assert_eq!(AnalysisContextKind::Rust.canonical_name(), "rust");
    }

    #[test]
    fn semantic_context_discovery_rejects_source_and_duplicate_candidates() {
        let request = AnalysisContextDiscoveryRequest {
            workspace_id: workspace_id(),
            source_generation: 1,
            source_paths: Vec::new(),
        };
        let semantic = AnalysisContextCandidate {
            context_kind: AnalysisContextKind::Python,
            provider_bundle_version: "providers-1".to_owned(),
            compiler_or_language_version: "3.14.7".to_owned(),
            configuration_manifest_uri: None,
            manifest_fingerprint: None,
            active: true,
        };
        assert_eq!(
            materialize_discovered_contexts(&request, vec![semantic.clone(), semantic]),
            Err(AnalysisContextError::DuplicateDiscoveredContext)
        );
        assert_eq!(
            materialize_discovered_contexts(
                &request,
                vec![AnalysisContextCandidate {
                    context_kind: AnalysisContextKind::Source,
                    provider_bundle_version: "source".to_owned(),
                    compiler_or_language_version: "source".to_owned(),
                    configuration_manifest_uri: None,
                    manifest_fingerprint: None,
                    active: true,
                }]
            ),
            Err(AnalysisContextError::DiscoveredSourceContext)
        );
    }
}
