// Retained operational SQLite/Arrow contracts.
//
// These contracts remain runtime inputs for the operational store. Durable semantic relation
// schemas are intentionally absent: v3 derives them from admitted Arrow schemas and plans.

const OPERATIONAL_TABLE_CONTRACTS: &[OperationalTableContract] = &[
    OperationalTableContract {
        name: "workspace_registration",
        sqlite_ddl: "CREATE TABLE workspace_registration (\n  workspace_id BLOB NOT NULL,\n  workspace_registration_nonce BLOB NOT NULL,\n  registration_revision INTEGER NOT NULL,\n  administrative_key BLOB NOT NULL,\n  root_path_bytes BLOB NOT NULL,\n  root_path_display TEXT NOT NULL,\n  root_directory_file_identity BLOB NOT NULL,\n  platform_code INTEGER NOT NULL,\n  case_sensitivity_mode TEXT NOT NULL,\n  authorization_revision INTEGER NOT NULL,\n  allowed_source_disclosure_rules BLOB NOT NULL,\n  repository_id BLOB,\n  worktree_id BLOB,\n  authorization_fingerprint BLOB NOT NULL,\n  context_fingerprint BLOB NOT NULL,\n  status_code INTEGER NOT NULL,\n  created_at TEXT NOT NULL,\n  updated_at TEXT NOT NULL,\n  PRIMARY KEY (workspace_id)\n) STRICT;\n",
        columns: &[
            OperationalColumnContract {
                name: "workspace_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("workspace"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "workspace_registration_nonce",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Binary,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "registration_revision",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "administrative_key",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Binary,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "root_path_bytes",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Binary,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "root_path_display",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "root_directory_file_identity",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Binary,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "platform_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "case_sensitivity_mode",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "authorization_revision",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "allowed_source_disclosure_rules",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Binary,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "repository_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("repository"),
                nullable: true,
            },
            OperationalColumnContract {
                name: "worktree_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("worktree"),
                nullable: true,
            },
            OperationalColumnContract {
                name: "authorization_fingerprint",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "context_fingerprint",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "status_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "created_at",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "updated_at",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: false,
            },
        ],
        primary_key: &["workspace_id"],
        workspace_scope: None,
    },
    OperationalTableContract {
        name: "workspace_generation",
        sqlite_ddl: "CREATE TABLE workspace_generation (\n  workspace_id BLOB NOT NULL,\n  source_generation INTEGER NOT NULL,\n  admitted_event_sequence INTEGER NOT NULL,\n  reconciled_event_sequence INTEGER NOT NULL,\n  durable_generation INTEGER NOT NULL,\n  updated_at TEXT NOT NULL,\n  PRIMARY KEY (workspace_id)\n) STRICT;\n",
        columns: &[
            OperationalColumnContract {
                name: "workspace_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("workspace"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "source_generation",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "admitted_event_sequence",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "reconciled_event_sequence",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "durable_generation",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "updated_at",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: false,
            },
        ],
        primary_key: &["workspace_id"],
        workspace_scope: None,
    },
    OperationalTableContract {
        name: "nested_root_exclusion",
        sqlite_ddl: "CREATE TABLE nested_root_exclusion (\n  parent_workspace_id BLOB NOT NULL,\n  child_workspace_id BLOB NOT NULL,\n  relative_path_bytes BLOB NOT NULL,\n  relative_path_display TEXT NOT NULL,\n  authorization_fingerprint BLOB NOT NULL,\n  created_at TEXT NOT NULL,\n  PRIMARY KEY (parent_workspace_id, child_workspace_id)\n) STRICT;\n",
        columns: &[
            OperationalColumnContract {
                name: "parent_workspace_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("workspace"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "child_workspace_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("workspace"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "relative_path_bytes",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Binary,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "relative_path_display",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "authorization_fingerprint",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "created_at",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: false,
            },
        ],
        primary_key: &["parent_workspace_id", "child_workspace_id"],
        workspace_scope: None,
    },
    OperationalTableContract {
        name: "credential_metadata",
        sqlite_ddl: "CREATE TABLE credential_metadata (\n  credential_id BLOB NOT NULL,\n  workspace_id BLOB NOT NULL,\n  agent_id TEXT NOT NULL,\n  credential_hash BLOB NOT NULL,\n  operations_mask INTEGER NOT NULL,\n  issued_at TEXT NOT NULL,\n  expires_at TEXT NOT NULL,\n  revoked_at TEXT,\n  revocation_reason_code INTEGER,\n  PRIMARY KEY (credential_id)\n) STRICT;\n",
        columns: &[
            OperationalColumnContract {
                name: "credential_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("observation"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "workspace_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("workspace"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "agent_id",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "credential_hash",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "operations_mask",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "issued_at",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "expires_at",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "revoked_at",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "revocation_reason_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: true,
            },
        ],
        primary_key: &["credential_id"],
        workspace_scope: None,
    },
    OperationalTableContract {
        name: "audit_event",
        sqlite_ddl: "CREATE TABLE audit_event (\n  event_id BLOB NOT NULL,\n  workspace_id BLOB,\n  event_code INTEGER NOT NULL,\n  actor_id TEXT NOT NULL,\n  occurred_at TEXT NOT NULL,\n  details_digest BLOB NOT NULL,\n  diagnostic_id BLOB,\n  PRIMARY KEY (event_id)\n) STRICT;\n",
        columns: &[
            OperationalColumnContract {
                name: "event_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("observation"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "workspace_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("workspace"),
                nullable: true,
            },
            OperationalColumnContract {
                name: "event_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "actor_id",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "occurred_at",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "details_digest",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "diagnostic_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("diagnostic"),
                nullable: true,
            },
        ],
        primary_key: &["event_id"],
        workspace_scope: None,
    },
    OperationalTableContract {
        name: "repository_registration",
        sqlite_ddl: "CREATE TABLE repository_registration (\n  repository_id BLOB NOT NULL,\n  repository_registration_nonce BLOB NOT NULL,\n  created_at TEXT NOT NULL,\n  PRIMARY KEY (repository_id)\n) STRICT;\n",
        columns: &[
            OperationalColumnContract {
                name: "repository_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("repository"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "repository_registration_nonce",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Binary,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "created_at",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: false,
            },
        ],
        primary_key: &["repository_id"],
        workspace_scope: None,
    },
    OperationalTableContract {
        name: "worktree_registration",
        sqlite_ddl: "CREATE TABLE worktree_registration (\n  worktree_id BLOB NOT NULL,\n  repository_id BLOB NOT NULL,\n  worktree_registration_nonce BLOB NOT NULL,\n  worktree_kind TEXT NOT NULL,\n  administrative_key BLOB NOT NULL,\n  created_at TEXT NOT NULL,\n  removed_at TEXT,\n  PRIMARY KEY (worktree_id)\n) STRICT;\n",
        columns: &[
            OperationalColumnContract {
                name: "worktree_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("worktree"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "repository_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("repository"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "worktree_registration_nonce",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Binary,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "worktree_kind",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "administrative_key",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Binary,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "created_at",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "removed_at",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: true,
            },
        ],
        primary_key: &["worktree_id"],
        workspace_scope: None,
    },
    OperationalTableContract {
        name: "common_repository_state",
        sqlite_ddl: "CREATE TABLE common_repository_state (\n  repository_id BLOB NOT NULL,\n  common_dir_path_bytes BLOB NOT NULL,\n  common_dir_path_display TEXT NOT NULL,\n  object_format_code INTEGER NOT NULL,\n  gix_version TEXT NOT NULL,\n  trust_policy_fingerprint BLOB NOT NULL,\n  worktree_count INTEGER NOT NULL,\n  git_health_code INTEGER NOT NULL,\n  updated_at TEXT NOT NULL,\n  last_diagnostic_id BLOB,\n  PRIMARY KEY (repository_id)\n) STRICT;\n",
        columns: &[
            OperationalColumnContract {
                name: "repository_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("repository"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "common_dir_path_bytes",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Binary,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "common_dir_path_display",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "object_format_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "gix_version",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "trust_policy_fingerprint",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "worktree_count",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "git_health_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "updated_at",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "last_diagnostic_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("diagnostic"),
                nullable: true,
            },
        ],
        primary_key: &["repository_id"],
        workspace_scope: Some(OperationalWorkspaceScope::ViaParent {
            parent_table: "worktree_state",
            child_column: "repository_id",
            parent_column: "repository_id",
            workspace_column: "workspace_id",
        }),
    },
    OperationalTableContract {
        name: "worktree_state",
        sqlite_ddl: "CREATE TABLE worktree_state (\n  workspace_id BLOB NOT NULL,\n  worktree_id BLOB,\n  repository_id BLOB,\n  work_dir_path_bytes BLOB NOT NULL,\n  work_dir_path_display TEXT NOT NULL,\n  git_dir_path_bytes BLOB,\n  git_dir_path_display TEXT,\n  lifecycle_state_code INTEGER NOT NULL,\n  source_trust_state_code INTEGER NOT NULL,\n  event_stream_health_code INTEGER NOT NULL,\n  git_acceleration_status_code INTEGER NOT NULL,\n  analysis_context_set_id BLOB NOT NULL,\n  source_generation INTEGER NOT NULL,\n  event_watermark INTEGER NOT NULL,\n  newest_dirty_generation INTEGER NOT NULL,\n  durable_generation INTEGER NOT NULL,\n  reconcile_required INTEGER NOT NULL,\n  updated_at TEXT NOT NULL,\n  last_diagnostic_id BLOB,\n  inventory_digest BLOB,\n  PRIMARY KEY (workspace_id),\n  UNIQUE (worktree_id)\n) STRICT;\n",
        columns: &[
            OperationalColumnContract {
                name: "workspace_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("workspace"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "worktree_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("worktree"),
                nullable: true,
            },
            OperationalColumnContract {
                name: "repository_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("repository"),
                nullable: true,
            },
            OperationalColumnContract {
                name: "work_dir_path_bytes",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Binary,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "work_dir_path_display",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "git_dir_path_bytes",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Binary,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "git_dir_path_display",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "lifecycle_state_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "source_trust_state_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "event_stream_health_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "git_acceleration_status_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "analysis_context_set_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("analysis_context_set"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "source_generation",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "event_watermark",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "newest_dirty_generation",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "durable_generation",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "reconcile_required",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "updated_at",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "last_diagnostic_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("diagnostic"),
                nullable: true,
            },
            OperationalColumnContract {
                name: "inventory_digest",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: true,
            },
        ],
        primary_key: &["workspace_id"],
        workspace_scope: Some(OperationalWorkspaceScope::Direct {
            workspace_column: "workspace_id",
        }),
    },
    OperationalTableContract {
        name: "source_inventory",
        sqlite_ddl: "CREATE TABLE source_inventory (\n  workspace_id BLOB NOT NULL,\n  source_generation INTEGER NOT NULL,\n  path_bytes BLOB NOT NULL,\n  path_display TEXT NOT NULL,\n  comparison_key_bytes BLOB NOT NULL,\n  file_id BLOB,\n  content_digest BLOB,\n  byte_length INTEGER NOT NULL,\n  file_kind_code INTEGER NOT NULL,\n  language_code TEXT,\n  inventory_classification_code INTEGER NOT NULL,\n  inclusion_state_code INTEGER NOT NULL,\n  git_repo_path_bytes BLOB,\n  git_blob_oid BLOB,\n  current_file_owner BLOB,\n  PRIMARY KEY (workspace_id, source_generation, path_bytes)\n) STRICT;\n",
        columns: &[
            OperationalColumnContract {
                name: "workspace_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("workspace"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "source_generation",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "path_bytes",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Binary,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "path_display",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "comparison_key_bytes",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Binary,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "file_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("source_file"),
                nullable: true,
            },
            OperationalColumnContract {
                name: "content_digest",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "byte_length",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "file_kind_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "language_code",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "inventory_classification_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "inclusion_state_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "git_repo_path_bytes",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Binary,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "git_blob_oid",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Binary,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "current_file_owner",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("owner"),
                nullable: true,
            },
        ],
        primary_key: &["workspace_id", "source_generation", "path_bytes"],
        workspace_scope: None,
    },
    OperationalTableContract {
        name: "source_blob",
        sqlite_ddl: "CREATE TABLE source_blob (\n  blob_digest BLOB NOT NULL,\n  byte_length INTEGER NOT NULL,\n  line_index_digest BLOB NOT NULL,\n  encoding_code INTEGER NOT NULL,\n  newline_code INTEGER NOT NULL,\n  created_at TEXT NOT NULL,\n  PRIMARY KEY (blob_digest)\n) STRICT;\n",
        columns: &[
            OperationalColumnContract {
                name: "blob_digest",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "byte_length",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "line_index_digest",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "encoding_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "newline_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "created_at",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: false,
            },
        ],
        primary_key: &["blob_digest"],
        workspace_scope: None,
    },
    OperationalTableContract {
        name: "source_blob_lease",
        sqlite_ddl: "CREATE TABLE source_blob_lease (\n  lease_id BLOB NOT NULL,\n  workspace_id BLOB NOT NULL,\n  source_generation INTEGER NOT NULL,\n  holder_kind_code INTEGER NOT NULL,\n  holder_id BLOB NOT NULL,\n  state_code INTEGER NOT NULL,\n  expires_at INTEGER NOT NULL,\n  orphaned_at INTEGER,\n  PRIMARY KEY (lease_id),\n  UNIQUE (workspace_id, source_generation, holder_kind_code, holder_id)\n) STRICT;\n",
        columns: &[
            OperationalColumnContract {
                name: "lease_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("observation"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "workspace_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("workspace"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "source_generation",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "holder_kind_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "holder_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("observation"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "state_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "expires_at",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "orphaned_at",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: true,
            },
        ],
        primary_key: &["lease_id"],
        workspace_scope: None,
    },
    OperationalTableContract {
        name: "source_blob_lease_member",
        sqlite_ddl: "CREATE TABLE source_blob_lease_member (\n  lease_id BLOB NOT NULL,\n  blob_digest BLOB NOT NULL,\n  PRIMARY KEY (lease_id, blob_digest)\n) STRICT;\n",
        columns: &[
            OperationalColumnContract {
                name: "lease_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("observation"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "blob_digest",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: false,
            },
        ],
        primary_key: &["lease_id", "blob_digest"],
        workspace_scope: None,
    },
    OperationalTableContract {
        name: "git_state_vector",
        sqlite_ddl: "CREATE TABLE git_state_vector (\n  workspace_id BLOB NOT NULL,\n  source_generation INTEGER NOT NULL,\n  repository_id BLOB NOT NULL,\n  worktree_id BLOB NOT NULL,\n  head_kind_code INTEGER NOT NULL,\n  head_target BLOB,\n  head_tree BLOB,\n  index_fingerprint BLOB,\n  index_entry_count INTEGER,\n  has_conflict_stages INTEGER NOT NULL,\n  repository_state_code INTEGER NOT NULL,\n  inclusion_policy_fingerprint BLOB NOT NULL,\n  attributes_fingerprint BLOB NOT NULL,\n  worktree_inventory_digest BLOB NOT NULL,\n  captured_at TEXT NOT NULL,\n  PRIMARY KEY (workspace_id, source_generation)\n) STRICT;\n",
        columns: &[
            OperationalColumnContract {
                name: "workspace_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("workspace"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "source_generation",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "repository_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("repository"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "worktree_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("worktree"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "head_kind_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "head_target",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Binary,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "head_tree",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Binary,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "index_fingerprint",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "index_entry_count",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "has_conflict_stages",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "repository_state_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "inclusion_policy_fingerprint",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "attributes_fingerprint",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "worktree_inventory_digest",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "captured_at",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: false,
            },
        ],
        primary_key: &["workspace_id", "source_generation"],
        workspace_scope: None,
    },
    OperationalTableContract {
        name: "update_wave",
        sqlite_ddl: "CREATE TABLE update_wave (\n  wave_id BLOB NOT NULL,\n  workspace_id BLOB NOT NULL,\n  source_generation INTEGER NOT NULL,\n  event_watermark INTEGER NOT NULL,\n  state_code INTEGER NOT NULL,\n  candidate_strategy_code INTEGER NOT NULL,\n  input_fingerprint BLOB NOT NULL,\n  candidate_count INTEGER NOT NULL,\n  started_at TEXT NOT NULL,\n  terminal_at TEXT,\n  diagnostic_id BLOB,\n  PRIMARY KEY (wave_id)\n) STRICT;\n",
        columns: &[
            OperationalColumnContract {
                name: "wave_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("observation"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "workspace_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("workspace"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "source_generation",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "event_watermark",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "state_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "candidate_strategy_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "input_fingerprint",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "candidate_count",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "started_at",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "terminal_at",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "diagnostic_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("diagnostic"),
                nullable: true,
            },
        ],
        primary_key: &["wave_id"],
        workspace_scope: Some(OperationalWorkspaceScope::Direct {
            workspace_column: "workspace_id",
        }),
    },
    OperationalTableContract {
        name: "update_wave_item",
        sqlite_ddl: "CREATE TABLE update_wave_item (\n  wave_id BLOB NOT NULL,\n  item_ordinal INTEGER NOT NULL,\n  path_bytes BLOB NOT NULL,\n  path_display TEXT NOT NULL,\n  path_encoding_code INTEGER NOT NULL,\n  state_code INTEGER NOT NULL,\n  input_fingerprint BLOB NOT NULL,\n  output_fingerprint BLOB,\n  diagnostic_id BLOB,\n  PRIMARY KEY (wave_id, item_ordinal)\n) STRICT;\n",
        columns: &[
            OperationalColumnContract {
                name: "wave_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("observation"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "item_ordinal",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "path_bytes",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Binary,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "path_display",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "path_encoding_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "state_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "input_fingerprint",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "output_fingerprint",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "diagnostic_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("diagnostic"),
                nullable: true,
            },
        ],
        primary_key: &["wave_id", "item_ordinal"],
        workspace_scope: Some(OperationalWorkspaceScope::ViaParent {
            parent_table: "update_wave",
            child_column: "wave_id",
            parent_column: "wave_id",
            workspace_column: "workspace_id",
        }),
    },
    OperationalTableContract {
        name: "operational_dependency_edge",
        sqlite_ddl: "CREATE TABLE operational_dependency_edge (\n  workspace_id BLOB NOT NULL,\n  source_owner_id BLOB NOT NULL,\n  dependent_owner_id BLOB NOT NULL,\n  edge_kind_code INTEGER NOT NULL,\n  derivation_id TEXT,\n  source_generation INTEGER NOT NULL,\n  input_digest BLOB NOT NULL,\n  active INTEGER NOT NULL,\n  PRIMARY KEY (workspace_id, source_owner_id, dependent_owner_id, edge_kind_code)\n) STRICT;\n",
        columns: &[
            OperationalColumnContract {
                name: "workspace_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("workspace"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "source_owner_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("owner"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "dependent_owner_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("owner"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "edge_kind_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "derivation_id",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "source_generation",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "input_digest",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "active",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
        ],
        primary_key: &[
            "workspace_id",
            "source_owner_id",
            "dependent_owner_id",
            "edge_kind_code",
        ],
        workspace_scope: Some(OperationalWorkspaceScope::Direct {
            workspace_column: "workspace_id",
        }),
    },
    OperationalTableContract {
        name: "provider_run",
        sqlite_ddl: "CREATE TABLE provider_run (\n  provider_run_id BLOB NOT NULL,\n  workspace_id BLOB NOT NULL,\n  analysis_context_id BLOB NOT NULL,\n  wave_id BLOB NOT NULL,\n  provider_code INTEGER NOT NULL,\n  owner_id BLOB,\n  build_unit_id BLOB,\n  source_generation INTEGER NOT NULL,\n  input_fingerprint BLOB NOT NULL,\n  output_fingerprint BLOB,\n  sandbox_profile_digest TEXT,\n  state_code INTEGER NOT NULL,\n  accepted_at TEXT NOT NULL,\n  terminal_at TEXT,\n  diagnostic_id BLOB,\n  PRIMARY KEY (provider_run_id)\n) STRICT;\n",
        columns: &[
            OperationalColumnContract {
                name: "provider_run_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("provider_run"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "workspace_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("workspace"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "analysis_context_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("analysis_context"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "wave_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("observation"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "provider_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "owner_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("owner"),
                nullable: true,
            },
            OperationalColumnContract {
                name: "build_unit_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("observation"),
                nullable: true,
            },
            OperationalColumnContract {
                name: "source_generation",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "input_fingerprint",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "output_fingerprint",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "sandbox_profile_digest",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "state_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "accepted_at",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "terminal_at",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "diagnostic_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("diagnostic"),
                nullable: true,
            },
        ],
        primary_key: &["provider_run_id"],
        workspace_scope: Some(OperationalWorkspaceScope::Direct {
            workspace_column: "workspace_id",
        }),
    },
    OperationalTableContract {
        name: "git_operation_run",
        sqlite_ddl: "CREATE TABLE git_operation_run (\n  git_operation_run_id BLOB NOT NULL,\n  workspace_id BLOB NOT NULL,\n  baseline_fingerprint BLOB NOT NULL,\n  result_fingerprint BLOB,\n  candidate_count INTEGER NOT NULL,\n  verified_count INTEGER NOT NULL,\n  state_code INTEGER NOT NULL,\n  started_at TEXT NOT NULL,\n  terminal_at TEXT,\n  diagnostic_id BLOB,\n  PRIMARY KEY (git_operation_run_id)\n) STRICT;\n",
        columns: &[
            OperationalColumnContract {
                name: "git_operation_run_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("observation"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "workspace_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("workspace"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "baseline_fingerprint",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "result_fingerprint",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "candidate_count",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "verified_count",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "state_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "started_at",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "terminal_at",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "diagnostic_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("diagnostic"),
                nullable: true,
            },
        ],
        primary_key: &["git_operation_run_id"],
        workspace_scope: Some(OperationalWorkspaceScope::Direct {
            workspace_column: "workspace_id",
        }),
    },
    OperationalTableContract {
        name: "git_candidate_cache",
        sqlite_ddl: "CREATE TABLE git_candidate_cache (\n  workspace_id BLOB NOT NULL,\n  worktree_id BLOB NOT NULL,\n  state_vector_digest BLOB NOT NULL,\n  topology_digest BLOB NOT NULL,\n  mode_code INTEGER NOT NULL,\n  candidate_payload BLOB NOT NULL,\n  payload_digest BLOB NOT NULL,\n  source_generation INTEGER NOT NULL,\n  PRIMARY KEY (workspace_id, worktree_id, state_vector_digest, topology_digest, mode_code)\n) STRICT;\n",
        columns: &[
            OperationalColumnContract {
                name: "workspace_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("workspace"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "worktree_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("worktree"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "state_vector_digest",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "topology_digest",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "mode_code",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "candidate_payload",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Binary,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "payload_digest",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "source_generation",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::Int64,
                id_domain: None,
                nullable: false,
            },
        ],
        primary_key: &[
            "workspace_id",
            "worktree_id",
            "state_vector_digest",
            "topology_digest",
            "mode_code",
        ],
        workspace_scope: Some(OperationalWorkspaceScope::Direct {
            workspace_column: "workspace_id",
        }),
    },
    OperationalTableContract {
        name: "result_artifact_lease",
        sqlite_ddl: "CREATE TABLE result_artifact_lease (\n  lease_id BLOB NOT NULL,\n  artifact_uri TEXT NOT NULL,\n  checksum BLOB NOT NULL,\n  expires_at INTEGER NOT NULL,\n  PRIMARY KEY (lease_id)\n) STRICT;\n",
        columns: &[
            OperationalColumnContract {
                name: "lease_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("observation"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "artifact_uri",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "checksum",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Hash32,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "expires_at",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: false,
            },
        ],
        primary_key: &["lease_id"],
        workspace_scope: None,
    },
    OperationalTableContract {
        name: "query_execution_terminal",
        sqlite_ddl: "CREATE TABLE query_execution_terminal (\n  execution_id TEXT NOT NULL,\n  workspace_id BLOB NOT NULL,\n  semantic_request_id TEXT NOT NULL,\n  mcp_call_id TEXT NOT NULL,\n  terminal_phase TEXT NOT NULL,\n  failing_stage TEXT,\n  bundle_checksum TEXT NOT NULL,\n  primary_payload_uri TEXT,\n  payload_status TEXT NOT NULL,\n  fallback_envelope_bytes BLOB,\n  snapshot_id TEXT,\n  publication_id TEXT,\n  source_table_versions_bytes BLOB NOT NULL,\n  created_at INTEGER NOT NULL,\n  expires_at INTEGER NOT NULL,\n  PRIMARY KEY (execution_id)\n) STRICT;\n",
        columns: &[
            OperationalColumnContract {
                name: "execution_id",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "workspace_id",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Id16,
                id_domain: Some("workspace"),
                nullable: false,
            },
            OperationalColumnContract {
                name: "semantic_request_id",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "mcp_call_id",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "terminal_phase",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "failing_stage",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "bundle_checksum",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "primary_payload_uri",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "payload_status",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "fallback_envelope_bytes",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Binary,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "snapshot_id",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "publication_id",
                sqlite_type: OperationalSqliteType::Text,
                logical_type: OperationalLogicalType::Utf8,
                id_domain: None,
                nullable: true,
            },
            OperationalColumnContract {
                name: "source_table_versions_bytes",
                sqlite_type: OperationalSqliteType::Blob,
                logical_type: OperationalLogicalType::Binary,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "created_at",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: false,
            },
            OperationalColumnContract {
                name: "expires_at",
                sqlite_type: OperationalSqliteType::Integer,
                logical_type: OperationalLogicalType::TimestampUtc,
                id_domain: None,
                nullable: false,
            },
        ],
        primary_key: &["execution_id"],
        workspace_scope: Some(OperationalWorkspaceScope::Direct {
            workspace_column: "workspace_id",
        }),
    },
];


